// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_AI_Agents_Mcp_1_H
#define WINRT_Windows_AI_Agents_Mcp_1_H
#include "winrt/impl/Windows.AI.Agents.Mcp.0.h"
WINRT_EXPORT namespace winrt::Windows::AI::Agents::Mcp
{
    struct __declspec(empty_bases) IMcpHttpConnectionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpHttpConnectionResult>
    {
        IMcpHttpConnectionResult(std::nullptr_t = nullptr) noexcept {}
        IMcpHttpConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpNamedPipeConnectionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpNamedPipeConnectionResult>
    {
        IMcpNamedPipeConnectionResult(std::nullptr_t = nullptr) noexcept {}
        IMcpNamedPipeConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpNamedPipeConnectionServer :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpNamedPipeConnectionServer>
    {
        IMcpNamedPipeConnectionServer(std::nullptr_t = nullptr) noexcept {}
        IMcpNamedPipeConnectionServer(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpResourcesStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpResourcesStatics>
    {
        IMcpResourcesStatics(std::nullptr_t = nullptr) noexcept {}
        IMcpResourcesStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpServerContext :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpServerContext>
    {
        IMcpServerContext(std::nullptr_t = nullptr) noexcept {}
        IMcpServerContext(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpServerContextStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpServerContextStatics>
    {
        IMcpServerContextStatics(std::nullptr_t = nullptr) noexcept {}
        IMcpServerContextStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpServerInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpServerInfo>
    {
        IMcpServerInfo(std::nullptr_t = nullptr) noexcept {}
        IMcpServerInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpServerRegistry :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpServerRegistry>
    {
        IMcpServerRegistry(std::nullptr_t = nullptr) noexcept {}
        IMcpServerRegistry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpServerRegistryStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpServerRegistryStatics>
    {
        IMcpServerRegistryStatics(std::nullptr_t = nullptr) noexcept {}
        IMcpServerRegistryStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpSseConnectionServer :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpSseConnectionServer>
    {
        IMcpSseConnectionServer(std::nullptr_t = nullptr) noexcept {}
        IMcpSseConnectionServer(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpStdioConnectionInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpStdioConnectionInfo>
    {
        IMcpStdioConnectionInfo(std::nullptr_t = nullptr) noexcept {}
        IMcpStdioConnectionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
