// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_AI_Agents_Mcp_2_H
#define WINRT_Windows_AI_Agents_Mcp_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.AI.Agents.Mcp.1.h"
WINRT_EXPORT namespace winrt::Windows::AI::Agents::Mcp
{
    struct __declspec(empty_bases) McpHttpConnectionResult : winrt::Windows::AI::Agents::Mcp::IMcpHttpConnectionResult
    {
        McpHttpConnectionResult(std::nullptr_t) noexcept {}
        McpHttpConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpHttpConnectionResult(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) McpNamedPipeConnectionResult : winrt::Windows::AI::Agents::Mcp::IMcpNamedPipeConnectionResult
    {
        McpNamedPipeConnectionResult(std::nullptr_t) noexcept {}
        McpNamedPipeConnectionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpNamedPipeConnectionResult(ptr, take_ownership_from_abi) {}
    };
    struct McpResources
    {
        McpResources() = delete;
        [[nodiscard]] static auto FileSystemRead();
        [[nodiscard]] static auto FileSystemWrite();
        [[nodiscard]] static auto FileSystemDelete();
        [[nodiscard]] static auto FileSystemCreate();
        [[nodiscard]] static auto HttpGet();
        [[nodiscard]] static auto HttpPost();
        [[nodiscard]] static auto HttpPut();
        [[nodiscard]] static auto HttpDelete();
    };
    struct __declspec(empty_bases) McpServerContext : winrt::Windows::AI::Agents::Mcp::IMcpServerContext
    {
        McpServerContext(std::nullptr_t) noexcept {}
        McpServerContext(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpServerContext(ptr, take_ownership_from_abi) {}
        static auto GetContextForCaller();
    };
    struct __declspec(empty_bases) McpServerInfo : winrt::Windows::AI::Agents::Mcp::IMcpServerInfo
    {
        McpServerInfo(std::nullptr_t) noexcept {}
        McpServerInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpServerInfo(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) McpServerRegistry : winrt::Windows::AI::Agents::Mcp::IMcpServerRegistry
    {
        McpServerRegistry(std::nullptr_t) noexcept {}
        McpServerRegistry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpServerRegistry(ptr, take_ownership_from_abi) {}
        static auto GetDefault();
    };
    struct __declspec(empty_bases) McpStdioConnectionInfo : winrt::Windows::AI::Agents::Mcp::IMcpStdioConnectionInfo,
        impl::require<McpStdioConnectionInfo, winrt::Windows::Foundation::IClosable>
    {
        McpStdioConnectionInfo(std::nullptr_t) noexcept {}
        McpStdioConnectionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpStdioConnectionInfo(ptr, take_ownership_from_abi) {}
    };
}
#endif
