// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NETWORKRUNTIME_NETWORKRUNTIME_H_
#define FLATBUFFERS_GENERATED_NETWORKRUNTIME_NETWORKRUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NetworkRuntime {

struct Vec3;

struct Quaternion;

struct PhysicsEntitySnapshot;
struct PhysicsEntitySnapshotBuilder;

struct PhysicsSnapshot;
struct PhysicsSnapshotBuilder;

struct SceneChangeEvent;
struct SceneChangeEventBuilder;

struct EntitySpawnEvent;
struct EntitySpawnEventBuilder;

struct EntityDespawnEvent;
struct EntityDespawnEventBuilder;

struct OwnershipTransferEvent;
struct OwnershipTransferEventBuilder;

struct HandshakeMessage;
struct HandshakeMessageBuilder;

struct AckMessage;
struct AckMessageBuilder;

struct NetworkMessage;
struct NetworkMessageBuilder;

enum class MessageType : int8_t {
  PHYSICS_SNAPSHOT = 0,
  SCENE_CHANGE = 1,
  ENTITY_SPAWN = 2,
  ENTITY_DESPAWN = 3,
  OWNERSHIP_TRANSFER = 4,
  HANDSHAKE = 5,
  ACK = 6,
  MIN = PHYSICS_SNAPSHOT,
  MAX = ACK
};

inline const MessageType (&EnumValuesMessageType())[7] {
  static const MessageType values[] = {
    MessageType::PHYSICS_SNAPSHOT,
    MessageType::SCENE_CHANGE,
    MessageType::ENTITY_SPAWN,
    MessageType::ENTITY_DESPAWN,
    MessageType::OWNERSHIP_TRANSFER,
    MessageType::HANDSHAKE,
    MessageType::ACK
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[8] = {
    "PHYSICS_SNAPSHOT",
    "SCENE_CHANGE",
    "ENTITY_SPAWN",
    "ENTITY_DESPAWN",
    "OWNERSHIP_TRANSFER",
    "HANDSHAKE",
    "ACK",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType::PHYSICS_SNAPSHOT, MessageType::ACK)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

enum class PeerID : int8_t {
  PEER_1 = 0,
  PEER_2 = 1,
  PEER_3 = 2,
  PEER_4 = 3,
  MIN = PEER_1,
  MAX = PEER_4
};

inline const PeerID (&EnumValuesPeerID())[4] {
  static const PeerID values[] = {
    PeerID::PEER_1,
    PeerID::PEER_2,
    PeerID::PEER_3,
    PeerID::PEER_4
  };
  return values;
}

inline const char * const *EnumNamesPeerID() {
  static const char * const names[5] = {
    "PEER_1",
    "PEER_2",
    "PEER_3",
    "PEER_4",
    nullptr
  };
  return names;
}

inline const char *EnumNamePeerID(PeerID e) {
  if (::flatbuffers::IsOutRange(e, PeerID::PEER_1, PeerID::PEER_4)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPeerID()[index];
}

enum class OwnershipType : int8_t {
  ONE = 0,
  TWO = 1,
  THREE = 2,
  FOUR = 3,
  MIN = ONE,
  MAX = FOUR
};

inline const OwnershipType (&EnumValuesOwnershipType())[4] {
  static const OwnershipType values[] = {
    OwnershipType::ONE,
    OwnershipType::TWO,
    OwnershipType::THREE,
    OwnershipType::FOUR
  };
  return values;
}

inline const char * const *EnumNamesOwnershipType() {
  static const char * const names[5] = {
    "ONE",
    "TWO",
    "THREE",
    "FOUR",
    nullptr
  };
  return names;
}

inline const char *EnumNameOwnershipType(OwnershipType e) {
  if (::flatbuffers::IsOutRange(e, OwnershipType::ONE, OwnershipType::FOUR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOwnershipType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Vec3::Traits {
  using type = Vec3;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quaternion FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  struct Traits;
  Quaternion()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Quaternion(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Quaternion, 16);

struct Quaternion::Traits {
  using type = Quaternion;
};

struct PhysicsEntitySnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsEntitySnapshotBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_OWNER = 6,
    VT_POSITION = 8,
    VT_ROTATION = 10,
    VT_LINEAR_VELOCITY = 12,
    VT_ANGULAR_VELOCITY = 14
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  NetworkRuntime::OwnershipType owner() const {
    return static_cast<NetworkRuntime::OwnershipType>(GetField<int8_t>(VT_OWNER, 0));
  }
  const NetworkRuntime::Vec3 *position() const {
    return GetStruct<const NetworkRuntime::Vec3 *>(VT_POSITION);
  }
  const NetworkRuntime::Quaternion *rotation() const {
    return GetStruct<const NetworkRuntime::Quaternion *>(VT_ROTATION);
  }
  const NetworkRuntime::Vec3 *linear_velocity() const {
    return GetStruct<const NetworkRuntime::Vec3 *>(VT_LINEAR_VELOCITY);
  }
  const NetworkRuntime::Vec3 *angular_velocity() const {
    return GetStruct<const NetworkRuntime::Vec3 *>(VT_ANGULAR_VELOCITY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_OWNER, 1) &&
           VerifyField<NetworkRuntime::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<NetworkRuntime::Quaternion>(verifier, VT_ROTATION, 4) &&
           VerifyField<NetworkRuntime::Vec3>(verifier, VT_LINEAR_VELOCITY, 4) &&
           VerifyField<NetworkRuntime::Vec3>(verifier, VT_ANGULAR_VELOCITY, 4) &&
           verifier.EndTable();
  }
};

struct PhysicsEntitySnapshotBuilder {
  typedef PhysicsEntitySnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(PhysicsEntitySnapshot::VT_ENTITY_ID, entity_id, 0);
  }
  void add_owner(NetworkRuntime::OwnershipType owner) {
    fbb_.AddElement<int8_t>(PhysicsEntitySnapshot::VT_OWNER, static_cast<int8_t>(owner), 0);
  }
  void add_position(const NetworkRuntime::Vec3 *position) {
    fbb_.AddStruct(PhysicsEntitySnapshot::VT_POSITION, position);
  }
  void add_rotation(const NetworkRuntime::Quaternion *rotation) {
    fbb_.AddStruct(PhysicsEntitySnapshot::VT_ROTATION, rotation);
  }
  void add_linear_velocity(const NetworkRuntime::Vec3 *linear_velocity) {
    fbb_.AddStruct(PhysicsEntitySnapshot::VT_LINEAR_VELOCITY, linear_velocity);
  }
  void add_angular_velocity(const NetworkRuntime::Vec3 *angular_velocity) {
    fbb_.AddStruct(PhysicsEntitySnapshot::VT_ANGULAR_VELOCITY, angular_velocity);
  }
  explicit PhysicsEntitySnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsEntitySnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsEntitySnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsEntitySnapshot> CreatePhysicsEntitySnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    NetworkRuntime::OwnershipType owner = NetworkRuntime::OwnershipType::ONE,
    const NetworkRuntime::Vec3 *position = nullptr,
    const NetworkRuntime::Quaternion *rotation = nullptr,
    const NetworkRuntime::Vec3 *linear_velocity = nullptr,
    const NetworkRuntime::Vec3 *angular_velocity = nullptr) {
  PhysicsEntitySnapshotBuilder builder_(_fbb);
  builder_.add_angular_velocity(angular_velocity);
  builder_.add_linear_velocity(linear_velocity);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  builder_.add_owner(owner);
  return builder_.Finish();
}

struct PhysicsEntitySnapshot::Traits {
  using type = PhysicsEntitySnapshot;
  static auto constexpr Create = CreatePhysicsEntitySnapshot;
};

struct PhysicsSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsSnapshotBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_PEER = 4,
    VT_SNAPSHOT_SEQUENCE = 6,
    VT_TICK_INDEX = 8,
    VT_TIMESTAMP_MS = 10,
    VT_ENTITIES = 12
  };
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  uint32_t snapshot_sequence() const {
    return GetField<uint32_t>(VT_SNAPSHOT_SEQUENCE, 0);
  }
  uint32_t tick_index() const {
    return GetField<uint32_t>(VT_TICK_INDEX, 0);
  }
  uint64_t timestamp_ms() const {
    return GetField<uint64_t>(VT_TIMESTAMP_MS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>> *entities() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>> *>(VT_ENTITIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           VerifyField<uint32_t>(verifier, VT_SNAPSHOT_SEQUENCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TICK_INDEX, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP_MS, 8) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           verifier.EndTable();
  }
};

struct PhysicsSnapshotBuilder {
  typedef PhysicsSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(PhysicsSnapshot::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  void add_snapshot_sequence(uint32_t snapshot_sequence) {
    fbb_.AddElement<uint32_t>(PhysicsSnapshot::VT_SNAPSHOT_SEQUENCE, snapshot_sequence, 0);
  }
  void add_tick_index(uint32_t tick_index) {
    fbb_.AddElement<uint32_t>(PhysicsSnapshot::VT_TICK_INDEX, tick_index, 0);
  }
  void add_timestamp_ms(uint64_t timestamp_ms) {
    fbb_.AddElement<uint64_t>(PhysicsSnapshot::VT_TIMESTAMP_MS, timestamp_ms, 0);
  }
  void add_entities(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>>> entities) {
    fbb_.AddOffset(PhysicsSnapshot::VT_ENTITIES, entities);
  }
  explicit PhysicsSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsSnapshot> CreatePhysicsSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1,
    uint32_t snapshot_sequence = 0,
    uint32_t tick_index = 0,
    uint64_t timestamp_ms = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>>> entities = 0) {
  PhysicsSnapshotBuilder builder_(_fbb);
  builder_.add_timestamp_ms(timestamp_ms);
  builder_.add_entities(entities);
  builder_.add_tick_index(tick_index);
  builder_.add_snapshot_sequence(snapshot_sequence);
  builder_.add_sender_peer(sender_peer);
  return builder_.Finish();
}

struct PhysicsSnapshot::Traits {
  using type = PhysicsSnapshot;
  static auto constexpr Create = CreatePhysicsSnapshot;
};

inline ::flatbuffers::Offset<PhysicsSnapshot> CreatePhysicsSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1,
    uint32_t snapshot_sequence = 0,
    uint32_t tick_index = 0,
    uint64_t timestamp_ms = 0,
    const std::vector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>> *entities = nullptr) {
  auto entities__ = entities ? _fbb.CreateVector<::flatbuffers::Offset<NetworkRuntime::PhysicsEntitySnapshot>>(*entities) : 0;
  return NetworkRuntime::CreatePhysicsSnapshot(
      _fbb,
      sender_peer,
      snapshot_sequence,
      tick_index,
      timestamp_ms,
      entities__);
}

struct SceneChangeEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneChangeEventBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_NAME = 4,
    VT_SENDER_PEER = 6
  };
  const ::flatbuffers::String *scene_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCENE_NAME);
  }
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SCENE_NAME) &&
           verifier.VerifyString(scene_name()) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           verifier.EndTable();
  }
};

struct SceneChangeEventBuilder {
  typedef SceneChangeEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_name(::flatbuffers::Offset<::flatbuffers::String> scene_name) {
    fbb_.AddOffset(SceneChangeEvent::VT_SCENE_NAME, scene_name);
  }
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(SceneChangeEvent::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  explicit SceneChangeEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneChangeEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneChangeEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneChangeEvent> CreateSceneChangeEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> scene_name = 0,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  SceneChangeEventBuilder builder_(_fbb);
  builder_.add_scene_name(scene_name);
  builder_.add_sender_peer(sender_peer);
  return builder_.Finish();
}

struct SceneChangeEvent::Traits {
  using type = SceneChangeEvent;
  static auto constexpr Create = CreateSceneChangeEvent;
};

inline ::flatbuffers::Offset<SceneChangeEvent> CreateSceneChangeEventDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *scene_name = nullptr,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  auto scene_name__ = scene_name ? _fbb.CreateString(scene_name) : 0;
  return NetworkRuntime::CreateSceneChangeEvent(
      _fbb,
      scene_name__,
      sender_peer);
}

struct EntitySpawnEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntitySpawnEventBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_OWNER = 6,
    VT_POSITION = 8,
    VT_ROTATION = 10,
    VT_ENTITY_TYPE = 12,
    VT_SENDER_PEER = 14
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  NetworkRuntime::OwnershipType owner() const {
    return static_cast<NetworkRuntime::OwnershipType>(GetField<int8_t>(VT_OWNER, 0));
  }
  const NetworkRuntime::Vec3 *position() const {
    return GetStruct<const NetworkRuntime::Vec3 *>(VT_POSITION);
  }
  const NetworkRuntime::Quaternion *rotation() const {
    return GetStruct<const NetworkRuntime::Quaternion *>(VT_ROTATION);
  }
  const ::flatbuffers::String *entity_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENTITY_TYPE);
  }
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_OWNER, 1) &&
           VerifyField<NetworkRuntime::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<NetworkRuntime::Quaternion>(verifier, VT_ROTATION, 4) &&
           VerifyOffset(verifier, VT_ENTITY_TYPE) &&
           verifier.VerifyString(entity_type()) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           verifier.EndTable();
  }
};

struct EntitySpawnEventBuilder {
  typedef EntitySpawnEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(EntitySpawnEvent::VT_ENTITY_ID, entity_id, 0);
  }
  void add_owner(NetworkRuntime::OwnershipType owner) {
    fbb_.AddElement<int8_t>(EntitySpawnEvent::VT_OWNER, static_cast<int8_t>(owner), 0);
  }
  void add_position(const NetworkRuntime::Vec3 *position) {
    fbb_.AddStruct(EntitySpawnEvent::VT_POSITION, position);
  }
  void add_rotation(const NetworkRuntime::Quaternion *rotation) {
    fbb_.AddStruct(EntitySpawnEvent::VT_ROTATION, rotation);
  }
  void add_entity_type(::flatbuffers::Offset<::flatbuffers::String> entity_type) {
    fbb_.AddOffset(EntitySpawnEvent::VT_ENTITY_TYPE, entity_type);
  }
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(EntitySpawnEvent::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  explicit EntitySpawnEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntitySpawnEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntitySpawnEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntitySpawnEvent> CreateEntitySpawnEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    NetworkRuntime::OwnershipType owner = NetworkRuntime::OwnershipType::ONE,
    const NetworkRuntime::Vec3 *position = nullptr,
    const NetworkRuntime::Quaternion *rotation = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> entity_type = 0,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  EntitySpawnEventBuilder builder_(_fbb);
  builder_.add_entity_type(entity_type);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  builder_.add_sender_peer(sender_peer);
  builder_.add_owner(owner);
  return builder_.Finish();
}

struct EntitySpawnEvent::Traits {
  using type = EntitySpawnEvent;
  static auto constexpr Create = CreateEntitySpawnEvent;
};

inline ::flatbuffers::Offset<EntitySpawnEvent> CreateEntitySpawnEventDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    NetworkRuntime::OwnershipType owner = NetworkRuntime::OwnershipType::ONE,
    const NetworkRuntime::Vec3 *position = nullptr,
    const NetworkRuntime::Quaternion *rotation = nullptr,
    const char *entity_type = nullptr,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  auto entity_type__ = entity_type ? _fbb.CreateString(entity_type) : 0;
  return NetworkRuntime::CreateEntitySpawnEvent(
      _fbb,
      entity_id,
      owner,
      position,
      rotation,
      entity_type__,
      sender_peer);
}

struct EntityDespawnEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityDespawnEventBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_SENDER_PEER = 6
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           verifier.EndTable();
  }
};

struct EntityDespawnEventBuilder {
  typedef EntityDespawnEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(EntityDespawnEvent::VT_ENTITY_ID, entity_id, 0);
  }
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(EntityDespawnEvent::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  explicit EntityDespawnEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityDespawnEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityDespawnEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityDespawnEvent> CreateEntityDespawnEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  EntityDespawnEventBuilder builder_(_fbb);
  builder_.add_entity_id(entity_id);
  builder_.add_sender_peer(sender_peer);
  return builder_.Finish();
}

struct EntityDespawnEvent::Traits {
  using type = EntityDespawnEvent;
  static auto constexpr Create = CreateEntityDespawnEvent;
};

struct OwnershipTransferEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OwnershipTransferEventBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_NEW_OWNER = 6,
    VT_SENDER_PEER = 8
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  NetworkRuntime::OwnershipType new_owner() const {
    return static_cast<NetworkRuntime::OwnershipType>(GetField<int8_t>(VT_NEW_OWNER, 0));
  }
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_NEW_OWNER, 1) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           verifier.EndTable();
  }
};

struct OwnershipTransferEventBuilder {
  typedef OwnershipTransferEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(OwnershipTransferEvent::VT_ENTITY_ID, entity_id, 0);
  }
  void add_new_owner(NetworkRuntime::OwnershipType new_owner) {
    fbb_.AddElement<int8_t>(OwnershipTransferEvent::VT_NEW_OWNER, static_cast<int8_t>(new_owner), 0);
  }
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(OwnershipTransferEvent::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  explicit OwnershipTransferEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OwnershipTransferEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OwnershipTransferEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OwnershipTransferEvent> CreateOwnershipTransferEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    NetworkRuntime::OwnershipType new_owner = NetworkRuntime::OwnershipType::ONE,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  OwnershipTransferEventBuilder builder_(_fbb);
  builder_.add_entity_id(entity_id);
  builder_.add_sender_peer(sender_peer);
  builder_.add_new_owner(new_owner);
  return builder_.Finish();
}

struct OwnershipTransferEvent::Traits {
  using type = OwnershipTransferEvent;
  static auto constexpr Create = CreateOwnershipTransferEvent;
};

struct HandshakeMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandshakeMessageBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_PEER = 4,
    VT_PROTOCOL_VERSION = 6,
    VT_LOCAL_PORT = 8,
    VT_READY = 10
  };
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  uint32_t protocol_version() const {
    return GetField<uint32_t>(VT_PROTOCOL_VERSION, 0);
  }
  uint16_t local_port() const {
    return GetField<uint16_t>(VT_LOCAL_PORT, 0);
  }
  bool ready() const {
    return GetField<uint8_t>(VT_READY, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           VerifyField<uint32_t>(verifier, VT_PROTOCOL_VERSION, 4) &&
           VerifyField<uint16_t>(verifier, VT_LOCAL_PORT, 2) &&
           VerifyField<uint8_t>(verifier, VT_READY, 1) &&
           verifier.EndTable();
  }
};

struct HandshakeMessageBuilder {
  typedef HandshakeMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(HandshakeMessage::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  void add_protocol_version(uint32_t protocol_version) {
    fbb_.AddElement<uint32_t>(HandshakeMessage::VT_PROTOCOL_VERSION, protocol_version, 0);
  }
  void add_local_port(uint16_t local_port) {
    fbb_.AddElement<uint16_t>(HandshakeMessage::VT_LOCAL_PORT, local_port, 0);
  }
  void add_ready(bool ready) {
    fbb_.AddElement<uint8_t>(HandshakeMessage::VT_READY, static_cast<uint8_t>(ready), 0);
  }
  explicit HandshakeMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HandshakeMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HandshakeMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HandshakeMessage> CreateHandshakeMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1,
    uint32_t protocol_version = 0,
    uint16_t local_port = 0,
    bool ready = false) {
  HandshakeMessageBuilder builder_(_fbb);
  builder_.add_protocol_version(protocol_version);
  builder_.add_local_port(local_port);
  builder_.add_ready(ready);
  builder_.add_sender_peer(sender_peer);
  return builder_.Finish();
}

struct HandshakeMessage::Traits {
  using type = HandshakeMessage;
  static auto constexpr Create = CreateHandshakeMessage;
};

struct AckMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AckMessageBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACKNOWLEDGED_SEQUENCE = 4,
    VT_SENDER_PEER = 6
  };
  uint32_t acknowledged_sequence() const {
    return GetField<uint32_t>(VT_ACKNOWLEDGED_SEQUENCE, 0);
  }
  NetworkRuntime::PeerID sender_peer() const {
    return static_cast<NetworkRuntime::PeerID>(GetField<int8_t>(VT_SENDER_PEER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ACKNOWLEDGED_SEQUENCE, 4) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER, 1) &&
           verifier.EndTable();
  }
};

struct AckMessageBuilder {
  typedef AckMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_acknowledged_sequence(uint32_t acknowledged_sequence) {
    fbb_.AddElement<uint32_t>(AckMessage::VT_ACKNOWLEDGED_SEQUENCE, acknowledged_sequence, 0);
  }
  void add_sender_peer(NetworkRuntime::PeerID sender_peer) {
    fbb_.AddElement<int8_t>(AckMessage::VT_SENDER_PEER, static_cast<int8_t>(sender_peer), 0);
  }
  explicit AckMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AckMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AckMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AckMessage> CreateAckMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t acknowledged_sequence = 0,
    NetworkRuntime::PeerID sender_peer = NetworkRuntime::PeerID::PEER_1) {
  AckMessageBuilder builder_(_fbb);
  builder_.add_acknowledged_sequence(acknowledged_sequence);
  builder_.add_sender_peer(sender_peer);
  return builder_.Finish();
}

struct AckMessage::Traits {
  using type = AckMessage;
  static auto constexpr Create = CreateAckMessage;
};

struct NetworkMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetworkMessageBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_PHYSICS_SNAPSHOT = 6,
    VT_SCENE_CHANGE = 8,
    VT_ENTITY_SPAWN = 10,
    VT_ENTITY_DESPAWN = 12,
    VT_OWNERSHIP_TRANSFER = 14,
    VT_HANDSHAKE = 16,
    VT_ACK = 18
  };
  NetworkRuntime::MessageType message_type() const {
    return static_cast<NetworkRuntime::MessageType>(GetField<int8_t>(VT_MESSAGE_TYPE, 0));
  }
  const NetworkRuntime::PhysicsSnapshot *physics_snapshot() const {
    return GetPointer<const NetworkRuntime::PhysicsSnapshot *>(VT_PHYSICS_SNAPSHOT);
  }
  const NetworkRuntime::SceneChangeEvent *scene_change() const {
    return GetPointer<const NetworkRuntime::SceneChangeEvent *>(VT_SCENE_CHANGE);
  }
  const NetworkRuntime::EntitySpawnEvent *entity_spawn() const {
    return GetPointer<const NetworkRuntime::EntitySpawnEvent *>(VT_ENTITY_SPAWN);
  }
  const NetworkRuntime::EntityDespawnEvent *entity_despawn() const {
    return GetPointer<const NetworkRuntime::EntityDespawnEvent *>(VT_ENTITY_DESPAWN);
  }
  const NetworkRuntime::OwnershipTransferEvent *ownership_transfer() const {
    return GetPointer<const NetworkRuntime::OwnershipTransferEvent *>(VT_OWNERSHIP_TRANSFER);
  }
  const NetworkRuntime::HandshakeMessage *handshake() const {
    return GetPointer<const NetworkRuntime::HandshakeMessage *>(VT_HANDSHAKE);
  }
  const NetworkRuntime::AckMessage *ack() const {
    return GetPointer<const NetworkRuntime::AckMessage *>(VT_ACK);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_MESSAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_PHYSICS_SNAPSHOT) &&
           verifier.VerifyTable(physics_snapshot()) &&
           VerifyOffset(verifier, VT_SCENE_CHANGE) &&
           verifier.VerifyTable(scene_change()) &&
           VerifyOffset(verifier, VT_ENTITY_SPAWN) &&
           verifier.VerifyTable(entity_spawn()) &&
           VerifyOffset(verifier, VT_ENTITY_DESPAWN) &&
           verifier.VerifyTable(entity_despawn()) &&
           VerifyOffset(verifier, VT_OWNERSHIP_TRANSFER) &&
           verifier.VerifyTable(ownership_transfer()) &&
           VerifyOffset(verifier, VT_HANDSHAKE) &&
           verifier.VerifyTable(handshake()) &&
           VerifyOffset(verifier, VT_ACK) &&
           verifier.VerifyTable(ack()) &&
           verifier.EndTable();
  }
};

struct NetworkMessageBuilder {
  typedef NetworkMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(NetworkRuntime::MessageType message_type) {
    fbb_.AddElement<int8_t>(NetworkMessage::VT_MESSAGE_TYPE, static_cast<int8_t>(message_type), 0);
  }
  void add_physics_snapshot(::flatbuffers::Offset<NetworkRuntime::PhysicsSnapshot> physics_snapshot) {
    fbb_.AddOffset(NetworkMessage::VT_PHYSICS_SNAPSHOT, physics_snapshot);
  }
  void add_scene_change(::flatbuffers::Offset<NetworkRuntime::SceneChangeEvent> scene_change) {
    fbb_.AddOffset(NetworkMessage::VT_SCENE_CHANGE, scene_change);
  }
  void add_entity_spawn(::flatbuffers::Offset<NetworkRuntime::EntitySpawnEvent> entity_spawn) {
    fbb_.AddOffset(NetworkMessage::VT_ENTITY_SPAWN, entity_spawn);
  }
  void add_entity_despawn(::flatbuffers::Offset<NetworkRuntime::EntityDespawnEvent> entity_despawn) {
    fbb_.AddOffset(NetworkMessage::VT_ENTITY_DESPAWN, entity_despawn);
  }
  void add_ownership_transfer(::flatbuffers::Offset<NetworkRuntime::OwnershipTransferEvent> ownership_transfer) {
    fbb_.AddOffset(NetworkMessage::VT_OWNERSHIP_TRANSFER, ownership_transfer);
  }
  void add_handshake(::flatbuffers::Offset<NetworkRuntime::HandshakeMessage> handshake) {
    fbb_.AddOffset(NetworkMessage::VT_HANDSHAKE, handshake);
  }
  void add_ack(::flatbuffers::Offset<NetworkRuntime::AckMessage> ack) {
    fbb_.AddOffset(NetworkMessage::VT_ACK, ack);
  }
  explicit NetworkMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetworkMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetworkMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetworkMessage> CreateNetworkMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NetworkRuntime::MessageType message_type = NetworkRuntime::MessageType::PHYSICS_SNAPSHOT,
    ::flatbuffers::Offset<NetworkRuntime::PhysicsSnapshot> physics_snapshot = 0,
    ::flatbuffers::Offset<NetworkRuntime::SceneChangeEvent> scene_change = 0,
    ::flatbuffers::Offset<NetworkRuntime::EntitySpawnEvent> entity_spawn = 0,
    ::flatbuffers::Offset<NetworkRuntime::EntityDespawnEvent> entity_despawn = 0,
    ::flatbuffers::Offset<NetworkRuntime::OwnershipTransferEvent> ownership_transfer = 0,
    ::flatbuffers::Offset<NetworkRuntime::HandshakeMessage> handshake = 0,
    ::flatbuffers::Offset<NetworkRuntime::AckMessage> ack = 0) {
  NetworkMessageBuilder builder_(_fbb);
  builder_.add_ack(ack);
  builder_.add_handshake(handshake);
  builder_.add_ownership_transfer(ownership_transfer);
  builder_.add_entity_despawn(entity_despawn);
  builder_.add_entity_spawn(entity_spawn);
  builder_.add_scene_change(scene_change);
  builder_.add_physics_snapshot(physics_snapshot);
  builder_.add_message_type(message_type);
  return builder_.Finish();
}

struct NetworkMessage::Traits {
  using type = NetworkMessage;
  static auto constexpr Create = CreateNetworkMessage;
};

inline const NetworkRuntime::NetworkMessage *GetNetworkMessage(const void *buf) {
  return ::flatbuffers::GetRoot<NetworkRuntime::NetworkMessage>(buf);
}

inline const NetworkRuntime::NetworkMessage *GetSizePrefixedNetworkMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NetworkRuntime::NetworkMessage>(buf);
}

template <bool B = false>
inline bool VerifyNetworkMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NetworkRuntime::NetworkMessage>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedNetworkMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NetworkRuntime::NetworkMessage>(nullptr);
}

inline void FinishNetworkMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetworkRuntime::NetworkMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNetworkMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NetworkRuntime::NetworkMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NetworkRuntime

#endif  // FLATBUFFERS_GENERATED_NETWORKRUNTIME_NETWORKRUNTIME_H_
