// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENE_SIMULATION_H_
#define FLATBUFFERS_GENERATED_SCENE_SIMULATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Simulation {

struct Vec3;

struct RotationEuler;

struct PhysicsState;

struct Transform;

struct FloatRange;

struct Vec3Range;

struct Camera;
struct CameraBuilder;

struct PerspectiveCamera;
struct PerspectiveCameraBuilder;

struct OrthographicCamera;
struct OrthographicCameraBuilder;

struct Sphere;
struct SphereBuilder;

struct Plane;
struct PlaneBuilder;

struct Capsule;
struct CapsuleBuilder;

struct Cylinder;
struct CylinderBuilder;

struct Cuboid;
struct CuboidBuilder;

struct StaticObject;
struct StaticObjectBuilder;

struct Waypoint;
struct WaypointBuilder;

struct AnimatedObject;
struct AnimatedObjectBuilder;

struct SimulatedObject;
struct SimulatedObjectBuilder;

struct Object;
struct ObjectBuilder;

struct Material;
struct MaterialBuilder;

struct MaterialInteraction;
struct MaterialInteractionBuilder;

struct RepeatingSpawn;
struct RepeatingSpawnBuilder;

struct SingleBurstSpawn;
struct SingleBurstSpawnBuilder;

struct FixedLocation;
struct FixedLocationBuilder;

struct RandomBox;
struct RandomBoxBuilder;

struct RandomSphere;
struct RandomSphereBuilder;

struct BaseSpawner;
struct BaseSpawnerBuilder;

struct SphereSpawner;
struct SphereSpawnerBuilder;

struct CylinderSpawner;
struct CylinderSpawnerBuilder;

struct CapsuleSpawner;
struct CapsuleSpawnerBuilder;

struct CuboidSpawner;
struct CuboidSpawnerBuilder;

struct Scene;
struct SceneBuilder;

enum CameraType : uint8_t {
  CameraType_NONE = 0,
  CameraType_PerspectiveCamera = 1,
  CameraType_OrthographicCamera = 2,
  CameraType_MIN = CameraType_NONE,
  CameraType_MAX = CameraType_OrthographicCamera
};

inline const CameraType (&EnumValuesCameraType())[3] {
  static const CameraType values[] = {
    CameraType_NONE,
    CameraType_PerspectiveCamera,
    CameraType_OrthographicCamera
  };
  return values;
}

inline const char * const *EnumNamesCameraType() {
  static const char * const names[4] = {
    "NONE",
    "PerspectiveCamera",
    "OrthographicCamera",
    nullptr
  };
  return names;
}

inline const char *EnumNameCameraType(CameraType e) {
  if (::flatbuffers::IsOutRange(e, CameraType_NONE, CameraType_OrthographicCamera)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCameraType()[index];
}

template<typename T> struct CameraTypeTraits {
  static const CameraType enum_value = CameraType_NONE;
};

template<> struct CameraTypeTraits<Simulation::PerspectiveCamera> {
  static const CameraType enum_value = CameraType_PerspectiveCamera;
};

template<> struct CameraTypeTraits<Simulation::OrthographicCamera> {
  static const CameraType enum_value = CameraType_OrthographicCamera;
};

template <bool B = false>
bool VerifyCameraType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CameraType type);
template <bool B = false>
bool VerifyCameraTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum Shape : uint8_t {
  Shape_NONE = 0,
  Shape_Sphere = 1,
  Shape_Plane = 2,
  Shape_Capsule = 3,
  Shape_Cylinder = 4,
  Shape_Cuboid = 5,
  Shape_MIN = Shape_NONE,
  Shape_MAX = Shape_Cuboid
};

inline const Shape (&EnumValuesShape())[6] {
  static const Shape values[] = {
    Shape_NONE,
    Shape_Sphere,
    Shape_Plane,
    Shape_Capsule,
    Shape_Cylinder,
    Shape_Cuboid
  };
  return values;
}

inline const char * const *EnumNamesShape() {
  static const char * const names[7] = {
    "NONE",
    "Sphere",
    "Plane",
    "Capsule",
    "Cylinder",
    "Cuboid",
    nullptr
  };
  return names;
}

inline const char *EnumNameShape(Shape e) {
  if (::flatbuffers::IsOutRange(e, Shape_NONE, Shape_Cuboid)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesShape()[index];
}

template<typename T> struct ShapeTraits {
  static const Shape enum_value = Shape_NONE;
};

template<> struct ShapeTraits<Simulation::Sphere> {
  static const Shape enum_value = Shape_Sphere;
};

template<> struct ShapeTraits<Simulation::Plane> {
  static const Shape enum_value = Shape_Plane;
};

template<> struct ShapeTraits<Simulation::Capsule> {
  static const Shape enum_value = Shape_Capsule;
};

template<> struct ShapeTraits<Simulation::Cylinder> {
  static const Shape enum_value = Shape_Cylinder;
};

template<> struct ShapeTraits<Simulation::Cuboid> {
  static const Shape enum_value = Shape_Cuboid;
};

template <bool B = false>
bool VerifyShape(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Shape type);
template <bool B = false>
bool VerifyShapeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum Behaviour : uint8_t {
  Behaviour_NONE = 0,
  Behaviour_StaticObject = 1,
  Behaviour_SimulatedObject = 2,
  Behaviour_AnimatedObject = 3,
  Behaviour_MIN = Behaviour_NONE,
  Behaviour_MAX = Behaviour_AnimatedObject
};

inline const Behaviour (&EnumValuesBehaviour())[4] {
  static const Behaviour values[] = {
    Behaviour_NONE,
    Behaviour_StaticObject,
    Behaviour_SimulatedObject,
    Behaviour_AnimatedObject
  };
  return values;
}

inline const char * const *EnumNamesBehaviour() {
  static const char * const names[5] = {
    "NONE",
    "StaticObject",
    "SimulatedObject",
    "AnimatedObject",
    nullptr
  };
  return names;
}

inline const char *EnumNameBehaviour(Behaviour e) {
  if (::flatbuffers::IsOutRange(e, Behaviour_NONE, Behaviour_AnimatedObject)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBehaviour()[index];
}

template<typename T> struct BehaviourTraits {
  static const Behaviour enum_value = Behaviour_NONE;
};

template<> struct BehaviourTraits<Simulation::StaticObject> {
  static const Behaviour enum_value = Behaviour_StaticObject;
};

template<> struct BehaviourTraits<Simulation::SimulatedObject> {
  static const Behaviour enum_value = Behaviour_SimulatedObject;
};

template<> struct BehaviourTraits<Simulation::AnimatedObject> {
  static const Behaviour enum_value = Behaviour_AnimatedObject;
};

template <bool B = false>
bool VerifyBehaviour(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Behaviour type);
template <bool B = false>
bool VerifyBehaviourVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum EasingType : int8_t {
  EasingType_LINEAR = 0,
  EasingType_SMOOTHSTEP = 1,
  EasingType_MIN = EasingType_LINEAR,
  EasingType_MAX = EasingType_SMOOTHSTEP
};

inline const EasingType (&EnumValuesEasingType())[2] {
  static const EasingType values[] = {
    EasingType_LINEAR,
    EasingType_SMOOTHSTEP
  };
  return values;
}

inline const char * const *EnumNamesEasingType() {
  static const char * const names[3] = {
    "LINEAR",
    "SMOOTHSTEP",
    nullptr
  };
  return names;
}

inline const char *EnumNameEasingType(EasingType e) {
  if (::flatbuffers::IsOutRange(e, EasingType_LINEAR, EasingType_SMOOTHSTEP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEasingType()[index];
}

enum PathMode : int8_t {
  PathMode_STOP = 0,
  PathMode_LOOP = 1,
  PathMode_REVERSE = 2,
  PathMode_MIN = PathMode_STOP,
  PathMode_MAX = PathMode_REVERSE
};

inline const PathMode (&EnumValuesPathMode())[3] {
  static const PathMode values[] = {
    PathMode_STOP,
    PathMode_LOOP,
    PathMode_REVERSE
  };
  return values;
}

inline const char * const *EnumNamesPathMode() {
  static const char * const names[4] = {
    "STOP",
    "LOOP",
    "REVERSE",
    nullptr
  };
  return names;
}

inline const char *EnumNamePathMode(PathMode e) {
  if (::flatbuffers::IsOutRange(e, PathMode_STOP, PathMode_REVERSE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPathMode()[index];
}

enum ObjectOwnerType : int8_t {
  ObjectOwnerType_ONE = 0,
  ObjectOwnerType_TWO = 1,
  ObjectOwnerType_THREE = 2,
  ObjectOwnerType_FOUR = 3,
  ObjectOwnerType_MIN = ObjectOwnerType_ONE,
  ObjectOwnerType_MAX = ObjectOwnerType_FOUR
};

inline const ObjectOwnerType (&EnumValuesObjectOwnerType())[4] {
  static const ObjectOwnerType values[] = {
    ObjectOwnerType_ONE,
    ObjectOwnerType_TWO,
    ObjectOwnerType_THREE,
    ObjectOwnerType_FOUR
  };
  return values;
}

inline const char * const *EnumNamesObjectOwnerType() {
  static const char * const names[5] = {
    "ONE",
    "TWO",
    "THREE",
    "FOUR",
    nullptr
  };
  return names;
}

inline const char *EnumNameObjectOwnerType(ObjectOwnerType e) {
  if (::flatbuffers::IsOutRange(e, ObjectOwnerType_ONE, ObjectOwnerType_FOUR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesObjectOwnerType()[index];
}

enum CollisionType : int8_t {
  CollisionType_SOLID = 0,
  CollisionType_CONTAINER = 1,
  CollisionType_MIN = CollisionType_SOLID,
  CollisionType_MAX = CollisionType_CONTAINER
};

inline const CollisionType (&EnumValuesCollisionType())[2] {
  static const CollisionType values[] = {
    CollisionType_SOLID,
    CollisionType_CONTAINER
  };
  return values;
}

inline const char * const *EnumNamesCollisionType() {
  static const char * const names[3] = {
    "SOLID",
    "CONTAINER",
    nullptr
  };
  return names;
}

inline const char *EnumNameCollisionType(CollisionType e) {
  if (::flatbuffers::IsOutRange(e, CollisionType_SOLID, CollisionType_CONTAINER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCollisionType()[index];
}

enum SpawnType : uint8_t {
  SpawnType_NONE = 0,
  SpawnType_SingleBurstSpawn = 1,
  SpawnType_RepeatingSpawn = 2,
  SpawnType_MIN = SpawnType_NONE,
  SpawnType_MAX = SpawnType_RepeatingSpawn
};

inline const SpawnType (&EnumValuesSpawnType())[3] {
  static const SpawnType values[] = {
    SpawnType_NONE,
    SpawnType_SingleBurstSpawn,
    SpawnType_RepeatingSpawn
  };
  return values;
}

inline const char * const *EnumNamesSpawnType() {
  static const char * const names[4] = {
    "NONE",
    "SingleBurstSpawn",
    "RepeatingSpawn",
    nullptr
  };
  return names;
}

inline const char *EnumNameSpawnType(SpawnType e) {
  if (::flatbuffers::IsOutRange(e, SpawnType_NONE, SpawnType_RepeatingSpawn)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSpawnType()[index];
}

template<typename T> struct SpawnTypeTraits {
  static const SpawnType enum_value = SpawnType_NONE;
};

template<> struct SpawnTypeTraits<Simulation::SingleBurstSpawn> {
  static const SpawnType enum_value = SpawnType_SingleBurstSpawn;
};

template<> struct SpawnTypeTraits<Simulation::RepeatingSpawn> {
  static const SpawnType enum_value = SpawnType_RepeatingSpawn;
};

template <bool B = false>
bool VerifySpawnType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnType type);
template <bool B = false>
bool VerifySpawnTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum SpawnLocation : uint8_t {
  SpawnLocation_NONE = 0,
  SpawnLocation_FixedLocation = 1,
  SpawnLocation_RandomBox = 2,
  SpawnLocation_RandomSphere = 3,
  SpawnLocation_MIN = SpawnLocation_NONE,
  SpawnLocation_MAX = SpawnLocation_RandomSphere
};

inline const SpawnLocation (&EnumValuesSpawnLocation())[4] {
  static const SpawnLocation values[] = {
    SpawnLocation_NONE,
    SpawnLocation_FixedLocation,
    SpawnLocation_RandomBox,
    SpawnLocation_RandomSphere
  };
  return values;
}

inline const char * const *EnumNamesSpawnLocation() {
  static const char * const names[5] = {
    "NONE",
    "FixedLocation",
    "RandomBox",
    "RandomSphere",
    nullptr
  };
  return names;
}

inline const char *EnumNameSpawnLocation(SpawnLocation e) {
  if (::flatbuffers::IsOutRange(e, SpawnLocation_NONE, SpawnLocation_RandomSphere)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSpawnLocation()[index];
}

template<typename T> struct SpawnLocationTraits {
  static const SpawnLocation enum_value = SpawnLocation_NONE;
};

template<> struct SpawnLocationTraits<Simulation::FixedLocation> {
  static const SpawnLocation enum_value = SpawnLocation_FixedLocation;
};

template<> struct SpawnLocationTraits<Simulation::RandomBox> {
  static const SpawnLocation enum_value = SpawnLocation_RandomBox;
};

template<> struct SpawnLocationTraits<Simulation::RandomSphere> {
  static const SpawnLocation enum_value = SpawnLocation_RandomSphere;
};

template <bool B = false>
bool VerifySpawnLocation(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnLocation type);
template <bool B = false>
bool VerifySpawnLocationVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum SpawnerOwnerType : int8_t {
  SpawnerOwnerType_ONE = 0,
  SpawnerOwnerType_TWO = 1,
  SpawnerOwnerType_THREE = 2,
  SpawnerOwnerType_FOUR = 3,
  SpawnerOwnerType_SEQUENTIAL = 4,
  SpawnerOwnerType_MIN = SpawnerOwnerType_ONE,
  SpawnerOwnerType_MAX = SpawnerOwnerType_SEQUENTIAL
};

inline const SpawnerOwnerType (&EnumValuesSpawnerOwnerType())[5] {
  static const SpawnerOwnerType values[] = {
    SpawnerOwnerType_ONE,
    SpawnerOwnerType_TWO,
    SpawnerOwnerType_THREE,
    SpawnerOwnerType_FOUR,
    SpawnerOwnerType_SEQUENTIAL
  };
  return values;
}

inline const char * const *EnumNamesSpawnerOwnerType() {
  static const char * const names[6] = {
    "ONE",
    "TWO",
    "THREE",
    "FOUR",
    "SEQUENTIAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameSpawnerOwnerType(SpawnerOwnerType e) {
  if (::flatbuffers::IsOutRange(e, SpawnerOwnerType_ONE, SpawnerOwnerType_SEQUENTIAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSpawnerOwnerType()[index];
}

enum SpawnerType : uint8_t {
  SpawnerType_NONE = 0,
  SpawnerType_SphereSpawner = 1,
  SpawnerType_CylinderSpawner = 2,
  SpawnerType_CapsuleSpawner = 3,
  SpawnerType_CuboidSpawner = 4,
  SpawnerType_MIN = SpawnerType_NONE,
  SpawnerType_MAX = SpawnerType_CuboidSpawner
};

inline const SpawnerType (&EnumValuesSpawnerType())[5] {
  static const SpawnerType values[] = {
    SpawnerType_NONE,
    SpawnerType_SphereSpawner,
    SpawnerType_CylinderSpawner,
    SpawnerType_CapsuleSpawner,
    SpawnerType_CuboidSpawner
  };
  return values;
}

inline const char * const *EnumNamesSpawnerType() {
  static const char * const names[6] = {
    "NONE",
    "SphereSpawner",
    "CylinderSpawner",
    "CapsuleSpawner",
    "CuboidSpawner",
    nullptr
  };
  return names;
}

inline const char *EnumNameSpawnerType(SpawnerType e) {
  if (::flatbuffers::IsOutRange(e, SpawnerType_NONE, SpawnerType_CuboidSpawner)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSpawnerType()[index];
}

template<typename T> struct SpawnerTypeTraits {
  static const SpawnerType enum_value = SpawnerType_NONE;
};

template<> struct SpawnerTypeTraits<Simulation::SphereSpawner> {
  static const SpawnerType enum_value = SpawnerType_SphereSpawner;
};

template<> struct SpawnerTypeTraits<Simulation::CylinderSpawner> {
  static const SpawnerType enum_value = SpawnerType_CylinderSpawner;
};

template<> struct SpawnerTypeTraits<Simulation::CapsuleSpawner> {
  static const SpawnerType enum_value = SpawnerType_CapsuleSpawner;
};

template<> struct SpawnerTypeTraits<Simulation::CuboidSpawner> {
  static const SpawnerType enum_value = SpawnerType_CuboidSpawner;
};

template <bool B = false>
bool VerifySpawnerType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnerType type);
template <bool B = false>
bool VerifySpawnerTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RotationEuler FLATBUFFERS_FINAL_CLASS {
 private:
  float yaw_;
  float pitch_;
  float roll_;

 public:
  RotationEuler()
      : yaw_(0),
        pitch_(0),
        roll_(0) {
  }
  RotationEuler(float _yaw, float _pitch, float _roll)
      : yaw_(::flatbuffers::EndianScalar(_yaw)),
        pitch_(::flatbuffers::EndianScalar(_pitch)),
        roll_(::flatbuffers::EndianScalar(_roll)) {
  }
  float yaw() const {
    return ::flatbuffers::EndianScalar(yaw_);
  }
  float pitch() const {
    return ::flatbuffers::EndianScalar(pitch_);
  }
  float roll() const {
    return ::flatbuffers::EndianScalar(roll_);
  }
};
FLATBUFFERS_STRUCT_END(RotationEuler, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PhysicsState FLATBUFFERS_FINAL_CLASS {
 private:
  Simulation::Vec3 linear_velocity_;
  Simulation::Vec3 angular_velocity_;

 public:
  PhysicsState()
      : linear_velocity_(),
        angular_velocity_() {
  }
  PhysicsState(const Simulation::Vec3 &_linear_velocity, const Simulation::Vec3 &_angular_velocity)
      : linear_velocity_(_linear_velocity),
        angular_velocity_(_angular_velocity) {
  }
  const Simulation::Vec3 &linear_velocity() const {
    return linear_velocity_;
  }
  const Simulation::Vec3 &angular_velocity() const {
    return angular_velocity_;
  }
};
FLATBUFFERS_STRUCT_END(PhysicsState, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Transform FLATBUFFERS_FINAL_CLASS {
 private:
  Simulation::Vec3 position_;
  Simulation::RotationEuler orientation_;
  Simulation::Vec3 scale_;

 public:
  Transform()
      : position_(),
        orientation_(),
        scale_() {
  }
  Transform(const Simulation::Vec3 &_position, const Simulation::RotationEuler &_orientation, const Simulation::Vec3 &_scale)
      : position_(_position),
        orientation_(_orientation),
        scale_(_scale) {
  }
  const Simulation::Vec3 &position() const {
    return position_;
  }
  const Simulation::RotationEuler &orientation() const {
    return orientation_;
  }
  const Simulation::Vec3 &scale() const {
    return scale_;
  }
};
FLATBUFFERS_STRUCT_END(Transform, 36);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) FloatRange FLATBUFFERS_FINAL_CLASS {
 private:
  float min_;
  float max_;

 public:
  FloatRange()
      : min_(0),
        max_(0) {
  }
  FloatRange(float _min, float _max)
      : min_(::flatbuffers::EndianScalar(_min)),
        max_(::flatbuffers::EndianScalar(_max)) {
  }
  float min() const {
    return ::flatbuffers::EndianScalar(min_);
  }
  float max() const {
    return ::flatbuffers::EndianScalar(max_);
  }
};
FLATBUFFERS_STRUCT_END(FloatRange, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3Range FLATBUFFERS_FINAL_CLASS {
 private:
  Simulation::Vec3 min_;
  Simulation::Vec3 max_;

 public:
  Vec3Range()
      : min_(),
        max_() {
  }
  Vec3Range(const Simulation::Vec3 &_min, const Simulation::Vec3 &_max)
      : min_(_min),
        max_(_max) {
  }
  const Simulation::Vec3 &min() const {
    return min_;
  }
  const Simulation::Vec3 &max() const {
    return max_;
  }
};
FLATBUFFERS_STRUCT_END(Vec3Range, 24);

struct Camera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TRANSFORM = 6,
    VT_CAMERA_TYPE_TYPE = 8,
    VT_CAMERA_TYPE = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const Simulation::Transform *transform() const {
    return GetStruct<const Simulation::Transform *>(VT_TRANSFORM);
  }
  Simulation::CameraType camera_type_type() const {
    return static_cast<Simulation::CameraType>(GetField<uint8_t>(VT_CAMERA_TYPE_TYPE, 0));
  }
  const void *camera_type() const {
    return GetPointer<const void *>(VT_CAMERA_TYPE);
  }
  template<typename T> const T *camera_type_as() const;
  const Simulation::PerspectiveCamera *camera_type_as_PerspectiveCamera() const {
    return camera_type_type() == Simulation::CameraType_PerspectiveCamera ? static_cast<const Simulation::PerspectiveCamera *>(camera_type()) : nullptr;
  }
  const Simulation::OrthographicCamera *camera_type_as_OrthographicCamera() const {
    return camera_type_type() == Simulation::CameraType_OrthographicCamera ? static_cast<const Simulation::OrthographicCamera *>(camera_type()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<Simulation::Transform>(verifier, VT_TRANSFORM, 4) &&
           VerifyField<uint8_t>(verifier, VT_CAMERA_TYPE_TYPE, 1) &&
           VerifyOffset(verifier, VT_CAMERA_TYPE) &&
           VerifyCameraType(verifier, camera_type(), camera_type_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Simulation::PerspectiveCamera *Camera::camera_type_as<Simulation::PerspectiveCamera>() const {
  return camera_type_as_PerspectiveCamera();
}

template<> inline const Simulation::OrthographicCamera *Camera::camera_type_as<Simulation::OrthographicCamera>() const {
  return camera_type_as_OrthographicCamera();
}

struct CameraBuilder {
  typedef Camera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Camera::VT_NAME, name);
  }
  void add_transform(const Simulation::Transform *transform) {
    fbb_.AddStruct(Camera::VT_TRANSFORM, transform);
  }
  void add_camera_type_type(Simulation::CameraType camera_type_type) {
    fbb_.AddElement<uint8_t>(Camera::VT_CAMERA_TYPE_TYPE, static_cast<uint8_t>(camera_type_type), 0);
  }
  void add_camera_type(::flatbuffers::Offset<void> camera_type) {
    fbb_.AddOffset(Camera::VT_CAMERA_TYPE, camera_type);
  }
  explicit CameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Camera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Camera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Camera> CreateCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const Simulation::Transform *transform = nullptr,
    Simulation::CameraType camera_type_type = Simulation::CameraType_NONE,
    ::flatbuffers::Offset<void> camera_type = 0) {
  CameraBuilder builder_(_fbb);
  builder_.add_camera_type(camera_type);
  builder_.add_transform(transform);
  builder_.add_name(name);
  builder_.add_camera_type_type(camera_type_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Camera> CreateCameraDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const Simulation::Transform *transform = nullptr,
    Simulation::CameraType camera_type_type = Simulation::CameraType_NONE,
    ::flatbuffers::Offset<void> camera_type = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Simulation::CreateCamera(
      _fbb,
      name__,
      transform,
      camera_type_type,
      camera_type);
}

struct PerspectiveCamera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PerspectiveCameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FOV = 4,
    VT_NEAR = 6,
    VT_FAR = 8
  };
  float fov() const {
    return GetField<float>(VT_FOV, 0.0f);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 0.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_FOV, 4) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           verifier.EndTable();
  }
};

struct PerspectiveCameraBuilder {
  typedef PerspectiveCamera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fov(float fov) {
    fbb_.AddElement<float>(PerspectiveCamera::VT_FOV, fov, 0.0f);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(PerspectiveCamera::VT_NEAR, near, 0.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(PerspectiveCamera::VT_FAR, far, 0.0f);
  }
  explicit PerspectiveCameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PerspectiveCamera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PerspectiveCamera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PerspectiveCamera> CreatePerspectiveCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float fov = 0.0f,
    float near = 0.0f,
    float far = 0.0f) {
  PerspectiveCameraBuilder builder_(_fbb);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_fov(fov);
  return builder_.Finish();
}

struct OrthographicCamera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OrthographicCameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_NEAR = 6,
    VT_FAR = 8
  };
  float size() const {
    return GetField<float>(VT_SIZE, 0.0f);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 0.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_SIZE, 4) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           verifier.EndTable();
  }
};

struct OrthographicCameraBuilder {
  typedef OrthographicCamera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_size(float size) {
    fbb_.AddElement<float>(OrthographicCamera::VT_SIZE, size, 0.0f);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(OrthographicCamera::VT_NEAR, near, 0.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(OrthographicCamera::VT_FAR, far, 0.0f);
  }
  explicit OrthographicCameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OrthographicCamera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OrthographicCamera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OrthographicCamera> CreateOrthographicCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float size = 0.0f,
    float near = 0.0f,
    float far = 0.0f) {
  OrthographicCameraBuilder builder_(_fbb);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_size(size);
  return builder_.Finish();
}

struct Sphere FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SphereBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RADIUS = 4
  };
  float radius() const {
    return GetField<float>(VT_RADIUS, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_RADIUS, 4) &&
           verifier.EndTable();
  }
};

struct SphereBuilder {
  typedef Sphere Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_radius(float radius) {
    fbb_.AddElement<float>(Sphere::VT_RADIUS, radius, 0.0f);
  }
  explicit SphereBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sphere> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sphere>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Sphere> CreateSphere(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float radius = 0.0f) {
  SphereBuilder builder_(_fbb);
  builder_.add_radius(radius);
  return builder_.Finish();
}

struct Plane FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlaneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NORMAL = 4
  };
  const Simulation::Vec3 *normal() const {
    return GetStruct<const Simulation::Vec3 *>(VT_NORMAL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Vec3>(verifier, VT_NORMAL, 4) &&
           verifier.EndTable();
  }
};

struct PlaneBuilder {
  typedef Plane Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_normal(const Simulation::Vec3 *normal) {
    fbb_.AddStruct(Plane::VT_NORMAL, normal);
  }
  explicit PlaneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Plane> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Plane>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Plane> CreatePlane(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Vec3 *normal = nullptr) {
  PlaneBuilder builder_(_fbb);
  builder_.add_normal(normal);
  return builder_.Finish();
}

struct Capsule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CapsuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RADIUS = 4,
    VT_HEIGHT = 6
  };
  float radius() const {
    return GetField<float>(VT_RADIUS, 0.0f);
  }
  float height() const {
    return GetField<float>(VT_HEIGHT, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_RADIUS, 4) &&
           VerifyField<float>(verifier, VT_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct CapsuleBuilder {
  typedef Capsule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_radius(float radius) {
    fbb_.AddElement<float>(Capsule::VT_RADIUS, radius, 0.0f);
  }
  void add_height(float height) {
    fbb_.AddElement<float>(Capsule::VT_HEIGHT, height, 0.0f);
  }
  explicit CapsuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Capsule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Capsule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Capsule> CreateCapsule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float radius = 0.0f,
    float height = 0.0f) {
  CapsuleBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_radius(radius);
  return builder_.Finish();
}

struct Cylinder FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CylinderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RADIUS = 4,
    VT_HEIGHT = 6
  };
  float radius() const {
    return GetField<float>(VT_RADIUS, 0.0f);
  }
  float height() const {
    return GetField<float>(VT_HEIGHT, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_RADIUS, 4) &&
           VerifyField<float>(verifier, VT_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct CylinderBuilder {
  typedef Cylinder Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_radius(float radius) {
    fbb_.AddElement<float>(Cylinder::VT_RADIUS, radius, 0.0f);
  }
  void add_height(float height) {
    fbb_.AddElement<float>(Cylinder::VT_HEIGHT, height, 0.0f);
  }
  explicit CylinderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Cylinder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Cylinder>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Cylinder> CreateCylinder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float radius = 0.0f,
    float height = 0.0f) {
  CylinderBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_radius(radius);
  return builder_.Finish();
}

struct Cuboid FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CuboidBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4
  };
  const Simulation::Vec3 *size() const {
    return GetStruct<const Simulation::Vec3 *>(VT_SIZE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Vec3>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct CuboidBuilder {
  typedef Cuboid Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_size(const Simulation::Vec3 *size) {
    fbb_.AddStruct(Cuboid::VT_SIZE, size);
  }
  explicit CuboidBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Cuboid> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Cuboid>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Cuboid> CreateCuboid(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Vec3 *size = nullptr) {
  CuboidBuilder builder_(_fbb);
  builder_.add_size(size);
  return builder_.Finish();
}

struct StaticObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StaticObjectBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StaticObjectBuilder {
  typedef StaticObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit StaticObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StaticObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StaticObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StaticObject> CreateStaticObject(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  StaticObjectBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Waypoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WaypointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ROTATION = 6,
    VT_TIME = 8
  };
  const Simulation::Vec3 *position() const {
    return GetStruct<const Simulation::Vec3 *>(VT_POSITION);
  }
  const Simulation::RotationEuler *rotation() const {
    return GetStruct<const Simulation::RotationEuler *>(VT_ROTATION);
  }
  float time() const {
    return GetField<float>(VT_TIME, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<Simulation::RotationEuler>(verifier, VT_ROTATION, 4) &&
           VerifyField<float>(verifier, VT_TIME, 4) &&
           verifier.EndTable();
  }
};

struct WaypointBuilder {
  typedef Waypoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const Simulation::Vec3 *position) {
    fbb_.AddStruct(Waypoint::VT_POSITION, position);
  }
  void add_rotation(const Simulation::RotationEuler *rotation) {
    fbb_.AddStruct(Waypoint::VT_ROTATION, rotation);
  }
  void add_time(float time) {
    fbb_.AddElement<float>(Waypoint::VT_TIME, time, 0.0f);
  }
  explicit WaypointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Waypoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Waypoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Waypoint> CreateWaypoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Vec3 *position = nullptr,
    const Simulation::RotationEuler *rotation = nullptr,
    float time = 0.0f) {
  WaypointBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  return builder_.Finish();
}

struct AnimatedObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimatedObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WAYPOINTS = 4,
    VT_TOTAL_DURATION = 6,
    VT_EASING = 8,
    VT_PATH_MODE = 10
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Waypoint>> *waypoints() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Waypoint>> *>(VT_WAYPOINTS);
  }
  float total_duration() const {
    return GetField<float>(VT_TOTAL_DURATION, 0.0f);
  }
  Simulation::EasingType easing() const {
    return static_cast<Simulation::EasingType>(GetField<int8_t>(VT_EASING, 0));
  }
  Simulation::PathMode path_mode() const {
    return static_cast<Simulation::PathMode>(GetField<int8_t>(VT_PATH_MODE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WAYPOINTS) &&
           verifier.VerifyVector(waypoints()) &&
           verifier.VerifyVectorOfTables(waypoints()) &&
           VerifyField<float>(verifier, VT_TOTAL_DURATION, 4) &&
           VerifyField<int8_t>(verifier, VT_EASING, 1) &&
           VerifyField<int8_t>(verifier, VT_PATH_MODE, 1) &&
           verifier.EndTable();
  }
};

struct AnimatedObjectBuilder {
  typedef AnimatedObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_waypoints(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Waypoint>>> waypoints) {
    fbb_.AddOffset(AnimatedObject::VT_WAYPOINTS, waypoints);
  }
  void add_total_duration(float total_duration) {
    fbb_.AddElement<float>(AnimatedObject::VT_TOTAL_DURATION, total_duration, 0.0f);
  }
  void add_easing(Simulation::EasingType easing) {
    fbb_.AddElement<int8_t>(AnimatedObject::VT_EASING, static_cast<int8_t>(easing), 0);
  }
  void add_path_mode(Simulation::PathMode path_mode) {
    fbb_.AddElement<int8_t>(AnimatedObject::VT_PATH_MODE, static_cast<int8_t>(path_mode), 0);
  }
  explicit AnimatedObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimatedObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimatedObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimatedObject> CreateAnimatedObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Waypoint>>> waypoints = 0,
    float total_duration = 0.0f,
    Simulation::EasingType easing = Simulation::EasingType_LINEAR,
    Simulation::PathMode path_mode = Simulation::PathMode_STOP) {
  AnimatedObjectBuilder builder_(_fbb);
  builder_.add_total_duration(total_duration);
  builder_.add_waypoints(waypoints);
  builder_.add_path_mode(path_mode);
  builder_.add_easing(easing);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimatedObject> CreateAnimatedObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Simulation::Waypoint>> *waypoints = nullptr,
    float total_duration = 0.0f,
    Simulation::EasingType easing = Simulation::EasingType_LINEAR,
    Simulation::PathMode path_mode = Simulation::PathMode_STOP) {
  auto waypoints__ = waypoints ? _fbb.CreateVector<::flatbuffers::Offset<Simulation::Waypoint>>(*waypoints) : 0;
  return Simulation::CreateAnimatedObject(
      _fbb,
      waypoints__,
      total_duration,
      easing,
      path_mode);
}

struct SimulatedObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimulatedObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INITIAL_STATE = 4,
    VT_OWNER = 6
  };
  const Simulation::PhysicsState *initial_state() const {
    return GetStruct<const Simulation::PhysicsState *>(VT_INITIAL_STATE);
  }
  Simulation::ObjectOwnerType owner() const {
    return static_cast<Simulation::ObjectOwnerType>(GetField<int8_t>(VT_OWNER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::PhysicsState>(verifier, VT_INITIAL_STATE, 4) &&
           VerifyField<int8_t>(verifier, VT_OWNER, 1) &&
           verifier.EndTable();
  }
};

struct SimulatedObjectBuilder {
  typedef SimulatedObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_initial_state(const Simulation::PhysicsState *initial_state) {
    fbb_.AddStruct(SimulatedObject::VT_INITIAL_STATE, initial_state);
  }
  void add_owner(Simulation::ObjectOwnerType owner) {
    fbb_.AddElement<int8_t>(SimulatedObject::VT_OWNER, static_cast<int8_t>(owner), 0);
  }
  explicit SimulatedObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SimulatedObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SimulatedObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SimulatedObject> CreateSimulatedObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::PhysicsState *initial_state = nullptr,
    Simulation::ObjectOwnerType owner = Simulation::ObjectOwnerType_ONE) {
  SimulatedObjectBuilder builder_(_fbb);
  builder_.add_initial_state(initial_state);
  builder_.add_owner(owner);
  return builder_.Finish();
}

struct Object FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TRANSFORM = 6,
    VT_MATERIAL = 8,
    VT_SHAPE_TYPE = 10,
    VT_SHAPE = 12,
    VT_BEHAVIOUR_TYPE = 14,
    VT_BEHAVIOUR = 16,
    VT_COLLISION_TYPE = 18
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const Simulation::Transform *transform() const {
    return GetStruct<const Simulation::Transform *>(VT_TRANSFORM);
  }
  const ::flatbuffers::String *material() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL);
  }
  Simulation::Shape shape_type() const {
    return static_cast<Simulation::Shape>(GetField<uint8_t>(VT_SHAPE_TYPE, 0));
  }
  const void *shape() const {
    return GetPointer<const void *>(VT_SHAPE);
  }
  template<typename T> const T *shape_as() const;
  const Simulation::Sphere *shape_as_Sphere() const {
    return shape_type() == Simulation::Shape_Sphere ? static_cast<const Simulation::Sphere *>(shape()) : nullptr;
  }
  const Simulation::Plane *shape_as_Plane() const {
    return shape_type() == Simulation::Shape_Plane ? static_cast<const Simulation::Plane *>(shape()) : nullptr;
  }
  const Simulation::Capsule *shape_as_Capsule() const {
    return shape_type() == Simulation::Shape_Capsule ? static_cast<const Simulation::Capsule *>(shape()) : nullptr;
  }
  const Simulation::Cylinder *shape_as_Cylinder() const {
    return shape_type() == Simulation::Shape_Cylinder ? static_cast<const Simulation::Cylinder *>(shape()) : nullptr;
  }
  const Simulation::Cuboid *shape_as_Cuboid() const {
    return shape_type() == Simulation::Shape_Cuboid ? static_cast<const Simulation::Cuboid *>(shape()) : nullptr;
  }
  Simulation::Behaviour behaviour_type() const {
    return static_cast<Simulation::Behaviour>(GetField<uint8_t>(VT_BEHAVIOUR_TYPE, 0));
  }
  const void *behaviour() const {
    return GetPointer<const void *>(VT_BEHAVIOUR);
  }
  template<typename T> const T *behaviour_as() const;
  const Simulation::StaticObject *behaviour_as_StaticObject() const {
    return behaviour_type() == Simulation::Behaviour_StaticObject ? static_cast<const Simulation::StaticObject *>(behaviour()) : nullptr;
  }
  const Simulation::SimulatedObject *behaviour_as_SimulatedObject() const {
    return behaviour_type() == Simulation::Behaviour_SimulatedObject ? static_cast<const Simulation::SimulatedObject *>(behaviour()) : nullptr;
  }
  const Simulation::AnimatedObject *behaviour_as_AnimatedObject() const {
    return behaviour_type() == Simulation::Behaviour_AnimatedObject ? static_cast<const Simulation::AnimatedObject *>(behaviour()) : nullptr;
  }
  Simulation::CollisionType collision_type() const {
    return static_cast<Simulation::CollisionType>(GetField<int8_t>(VT_COLLISION_TYPE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<Simulation::Transform>(verifier, VT_TRANSFORM, 4) &&
           VerifyOffset(verifier, VT_MATERIAL) &&
           verifier.VerifyString(material()) &&
           VerifyField<uint8_t>(verifier, VT_SHAPE_TYPE, 1) &&
           VerifyOffset(verifier, VT_SHAPE) &&
           VerifyShape(verifier, shape(), shape_type()) &&
           VerifyField<uint8_t>(verifier, VT_BEHAVIOUR_TYPE, 1) &&
           VerifyOffset(verifier, VT_BEHAVIOUR) &&
           VerifyBehaviour(verifier, behaviour(), behaviour_type()) &&
           VerifyField<int8_t>(verifier, VT_COLLISION_TYPE, 1) &&
           verifier.EndTable();
  }
};

template<> inline const Simulation::Sphere *Object::shape_as<Simulation::Sphere>() const {
  return shape_as_Sphere();
}

template<> inline const Simulation::Plane *Object::shape_as<Simulation::Plane>() const {
  return shape_as_Plane();
}

template<> inline const Simulation::Capsule *Object::shape_as<Simulation::Capsule>() const {
  return shape_as_Capsule();
}

template<> inline const Simulation::Cylinder *Object::shape_as<Simulation::Cylinder>() const {
  return shape_as_Cylinder();
}

template<> inline const Simulation::Cuboid *Object::shape_as<Simulation::Cuboid>() const {
  return shape_as_Cuboid();
}

template<> inline const Simulation::StaticObject *Object::behaviour_as<Simulation::StaticObject>() const {
  return behaviour_as_StaticObject();
}

template<> inline const Simulation::SimulatedObject *Object::behaviour_as<Simulation::SimulatedObject>() const {
  return behaviour_as_SimulatedObject();
}

template<> inline const Simulation::AnimatedObject *Object::behaviour_as<Simulation::AnimatedObject>() const {
  return behaviour_as_AnimatedObject();
}

struct ObjectBuilder {
  typedef Object Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Object::VT_NAME, name);
  }
  void add_transform(const Simulation::Transform *transform) {
    fbb_.AddStruct(Object::VT_TRANSFORM, transform);
  }
  void add_material(::flatbuffers::Offset<::flatbuffers::String> material) {
    fbb_.AddOffset(Object::VT_MATERIAL, material);
  }
  void add_shape_type(Simulation::Shape shape_type) {
    fbb_.AddElement<uint8_t>(Object::VT_SHAPE_TYPE, static_cast<uint8_t>(shape_type), 0);
  }
  void add_shape(::flatbuffers::Offset<void> shape) {
    fbb_.AddOffset(Object::VT_SHAPE, shape);
  }
  void add_behaviour_type(Simulation::Behaviour behaviour_type) {
    fbb_.AddElement<uint8_t>(Object::VT_BEHAVIOUR_TYPE, static_cast<uint8_t>(behaviour_type), 0);
  }
  void add_behaviour(::flatbuffers::Offset<void> behaviour) {
    fbb_.AddOffset(Object::VT_BEHAVIOUR, behaviour);
  }
  void add_collision_type(Simulation::CollisionType collision_type) {
    fbb_.AddElement<int8_t>(Object::VT_COLLISION_TYPE, static_cast<int8_t>(collision_type), 0);
  }
  explicit ObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Object> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Object>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Object> CreateObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const Simulation::Transform *transform = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> material = 0,
    Simulation::Shape shape_type = Simulation::Shape_NONE,
    ::flatbuffers::Offset<void> shape = 0,
    Simulation::Behaviour behaviour_type = Simulation::Behaviour_NONE,
    ::flatbuffers::Offset<void> behaviour = 0,
    Simulation::CollisionType collision_type = Simulation::CollisionType_SOLID) {
  ObjectBuilder builder_(_fbb);
  builder_.add_behaviour(behaviour);
  builder_.add_shape(shape);
  builder_.add_material(material);
  builder_.add_transform(transform);
  builder_.add_name(name);
  builder_.add_collision_type(collision_type);
  builder_.add_behaviour_type(behaviour_type);
  builder_.add_shape_type(shape_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Object> CreateObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const Simulation::Transform *transform = nullptr,
    const char *material = nullptr,
    Simulation::Shape shape_type = Simulation::Shape_NONE,
    ::flatbuffers::Offset<void> shape = 0,
    Simulation::Behaviour behaviour_type = Simulation::Behaviour_NONE,
    ::flatbuffers::Offset<void> behaviour = 0,
    Simulation::CollisionType collision_type = Simulation::CollisionType_SOLID) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto material__ = material ? _fbb.CreateString(material) : 0;
  return Simulation::CreateObject(
      _fbb,
      name__,
      transform,
      material__,
      shape_type,
      shape,
      behaviour_type,
      behaviour,
      collision_type);
}

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DENSITY = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float density() const {
    return GetField<float>(VT_DENSITY, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_DENSITY, 4) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Material::VT_NAME, name);
  }
  void add_density(float density) {
    fbb_.AddElement<float>(Material::VT_DENSITY, density, 0.0f);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float density = 0.0f) {
  MaterialBuilder builder_(_fbb);
  builder_.add_density(density);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float density = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Simulation::CreateMaterial(
      _fbb,
      name__,
      density);
}

struct MaterialInteraction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialInteractionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATERIAL_A = 4,
    VT_MATERIAL_B = 6,
    VT_RESTITUTION = 8,
    VT_STATIC_FRICTION = 10,
    VT_DYNAMIC_FRICTION = 12
  };
  const ::flatbuffers::String *material_a() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL_A);
  }
  const ::flatbuffers::String *material_b() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL_B);
  }
  float restitution() const {
    return GetField<float>(VT_RESTITUTION, 0.0f);
  }
  float static_friction() const {
    return GetField<float>(VT_STATIC_FRICTION, 0.0f);
  }
  float dynamic_friction() const {
    return GetField<float>(VT_DYNAMIC_FRICTION, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MATERIAL_A) &&
           verifier.VerifyString(material_a()) &&
           VerifyOffset(verifier, VT_MATERIAL_B) &&
           verifier.VerifyString(material_b()) &&
           VerifyField<float>(verifier, VT_RESTITUTION, 4) &&
           VerifyField<float>(verifier, VT_STATIC_FRICTION, 4) &&
           VerifyField<float>(verifier, VT_DYNAMIC_FRICTION, 4) &&
           verifier.EndTable();
  }
};

struct MaterialInteractionBuilder {
  typedef MaterialInteraction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_material_a(::flatbuffers::Offset<::flatbuffers::String> material_a) {
    fbb_.AddOffset(MaterialInteraction::VT_MATERIAL_A, material_a);
  }
  void add_material_b(::flatbuffers::Offset<::flatbuffers::String> material_b) {
    fbb_.AddOffset(MaterialInteraction::VT_MATERIAL_B, material_b);
  }
  void add_restitution(float restitution) {
    fbb_.AddElement<float>(MaterialInteraction::VT_RESTITUTION, restitution, 0.0f);
  }
  void add_static_friction(float static_friction) {
    fbb_.AddElement<float>(MaterialInteraction::VT_STATIC_FRICTION, static_friction, 0.0f);
  }
  void add_dynamic_friction(float dynamic_friction) {
    fbb_.AddElement<float>(MaterialInteraction::VT_DYNAMIC_FRICTION, dynamic_friction, 0.0f);
  }
  explicit MaterialInteractionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialInteraction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialInteraction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialInteraction> CreateMaterialInteraction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> material_a = 0,
    ::flatbuffers::Offset<::flatbuffers::String> material_b = 0,
    float restitution = 0.0f,
    float static_friction = 0.0f,
    float dynamic_friction = 0.0f) {
  MaterialInteractionBuilder builder_(_fbb);
  builder_.add_dynamic_friction(dynamic_friction);
  builder_.add_static_friction(static_friction);
  builder_.add_restitution(restitution);
  builder_.add_material_b(material_b);
  builder_.add_material_a(material_a);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialInteraction> CreateMaterialInteractionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *material_a = nullptr,
    const char *material_b = nullptr,
    float restitution = 0.0f,
    float static_friction = 0.0f,
    float dynamic_friction = 0.0f) {
  auto material_a__ = material_a ? _fbb.CreateString(material_a) : 0;
  auto material_b__ = material_b ? _fbb.CreateString(material_b) : 0;
  return Simulation::CreateMaterialInteraction(
      _fbb,
      material_a__,
      material_b__,
      restitution,
      static_friction,
      dynamic_friction);
}

struct RepeatingSpawn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RepeatingSpawnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERVAL = 4,
    VT_MAX_COUNT = 6
  };
  float interval() const {
    return GetField<float>(VT_INTERVAL, 0.0f);
  }
  uint32_t max_count() const {
    return GetField<uint32_t>(VT_MAX_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_INTERVAL, 4) &&
           VerifyField<uint32_t>(verifier, VT_MAX_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct RepeatingSpawnBuilder {
  typedef RepeatingSpawn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interval(float interval) {
    fbb_.AddElement<float>(RepeatingSpawn::VT_INTERVAL, interval, 0.0f);
  }
  void add_max_count(uint32_t max_count) {
    fbb_.AddElement<uint32_t>(RepeatingSpawn::VT_MAX_COUNT, max_count, 0);
  }
  explicit RepeatingSpawnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RepeatingSpawn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RepeatingSpawn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RepeatingSpawn> CreateRepeatingSpawn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float interval = 0.0f,
    uint32_t max_count = 0) {
  RepeatingSpawnBuilder builder_(_fbb);
  builder_.add_max_count(max_count);
  builder_.add_interval(interval);
  return builder_.Finish();
}

struct SingleBurstSpawn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SingleBurstSpawnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COUNT = 4
  };
  uint32_t count() const {
    return GetField<uint32_t>(VT_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct SingleBurstSpawnBuilder {
  typedef SingleBurstSpawn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_count(uint32_t count) {
    fbb_.AddElement<uint32_t>(SingleBurstSpawn::VT_COUNT, count, 0);
  }
  explicit SingleBurstSpawnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SingleBurstSpawn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SingleBurstSpawn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SingleBurstSpawn> CreateSingleBurstSpawn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t count = 0) {
  SingleBurstSpawnBuilder builder_(_fbb);
  builder_.add_count(count);
  return builder_.Finish();
}

struct FixedLocation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FixedLocationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSFORM = 4
  };
  const Simulation::Transform *transform() const {
    return GetStruct<const Simulation::Transform *>(VT_TRANSFORM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Transform>(verifier, VT_TRANSFORM, 4) &&
           verifier.EndTable();
  }
};

struct FixedLocationBuilder {
  typedef FixedLocation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transform(const Simulation::Transform *transform) {
    fbb_.AddStruct(FixedLocation::VT_TRANSFORM, transform);
  }
  explicit FixedLocationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FixedLocation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FixedLocation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FixedLocation> CreateFixedLocation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Transform *transform = nullptr) {
  FixedLocationBuilder builder_(_fbb);
  builder_.add_transform(transform);
  return builder_.Finish();
}

struct RandomBox FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RandomBoxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MIN = 4,
    VT_MAX = 6
  };
  const Simulation::Vec3 *min() const {
    return GetStruct<const Simulation::Vec3 *>(VT_MIN);
  }
  const Simulation::Vec3 *max() const {
    return GetStruct<const Simulation::Vec3 *>(VT_MAX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Vec3>(verifier, VT_MIN, 4) &&
           VerifyField<Simulation::Vec3>(verifier, VT_MAX, 4) &&
           verifier.EndTable();
  }
};

struct RandomBoxBuilder {
  typedef RandomBox Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_min(const Simulation::Vec3 *min) {
    fbb_.AddStruct(RandomBox::VT_MIN, min);
  }
  void add_max(const Simulation::Vec3 *max) {
    fbb_.AddStruct(RandomBox::VT_MAX, max);
  }
  explicit RandomBoxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RandomBox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RandomBox>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RandomBox> CreateRandomBox(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Vec3 *min = nullptr,
    const Simulation::Vec3 *max = nullptr) {
  RandomBoxBuilder builder_(_fbb);
  builder_.add_max(max);
  builder_.add_min(min);
  return builder_.Finish();
}

struct RandomSphere FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RandomSphereBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CENTER = 4,
    VT_RADIUS = 6
  };
  const Simulation::Vec3 *center() const {
    return GetStruct<const Simulation::Vec3 *>(VT_CENTER);
  }
  float radius() const {
    return GetField<float>(VT_RADIUS, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Simulation::Vec3>(verifier, VT_CENTER, 4) &&
           VerifyField<float>(verifier, VT_RADIUS, 4) &&
           verifier.EndTable();
  }
};

struct RandomSphereBuilder {
  typedef RandomSphere Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_center(const Simulation::Vec3 *center) {
    fbb_.AddStruct(RandomSphere::VT_CENTER, center);
  }
  void add_radius(float radius) {
    fbb_.AddElement<float>(RandomSphere::VT_RADIUS, radius, 0.0f);
  }
  explicit RandomSphereBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RandomSphere> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RandomSphere>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RandomSphere> CreateRandomSphere(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Simulation::Vec3 *center = nullptr,
    float radius = 0.0f) {
  RandomSphereBuilder builder_(_fbb);
  builder_.add_radius(radius);
  builder_.add_center(center);
  return builder_.Finish();
}

struct BaseSpawner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BaseSpawnerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_START_TIME = 6,
    VT_SPAWN_TYPE_TYPE = 8,
    VT_SPAWN_TYPE = 10,
    VT_LOCATION_TYPE = 12,
    VT_LOCATION = 14,
    VT_LINEAR_VELOCITY = 16,
    VT_ANGULAR_VELOCITY = 18,
    VT_MATERIAL = 20,
    VT_OWNER = 22
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float start_time() const {
    return GetField<float>(VT_START_TIME, 0.0f);
  }
  Simulation::SpawnType spawn_type_type() const {
    return static_cast<Simulation::SpawnType>(GetField<uint8_t>(VT_SPAWN_TYPE_TYPE, 0));
  }
  const void *spawn_type() const {
    return GetPointer<const void *>(VT_SPAWN_TYPE);
  }
  template<typename T> const T *spawn_type_as() const;
  const Simulation::SingleBurstSpawn *spawn_type_as_SingleBurstSpawn() const {
    return spawn_type_type() == Simulation::SpawnType_SingleBurstSpawn ? static_cast<const Simulation::SingleBurstSpawn *>(spawn_type()) : nullptr;
  }
  const Simulation::RepeatingSpawn *spawn_type_as_RepeatingSpawn() const {
    return spawn_type_type() == Simulation::SpawnType_RepeatingSpawn ? static_cast<const Simulation::RepeatingSpawn *>(spawn_type()) : nullptr;
  }
  Simulation::SpawnLocation location_type() const {
    return static_cast<Simulation::SpawnLocation>(GetField<uint8_t>(VT_LOCATION_TYPE, 0));
  }
  const void *location() const {
    return GetPointer<const void *>(VT_LOCATION);
  }
  template<typename T> const T *location_as() const;
  const Simulation::FixedLocation *location_as_FixedLocation() const {
    return location_type() == Simulation::SpawnLocation_FixedLocation ? static_cast<const Simulation::FixedLocation *>(location()) : nullptr;
  }
  const Simulation::RandomBox *location_as_RandomBox() const {
    return location_type() == Simulation::SpawnLocation_RandomBox ? static_cast<const Simulation::RandomBox *>(location()) : nullptr;
  }
  const Simulation::RandomSphere *location_as_RandomSphere() const {
    return location_type() == Simulation::SpawnLocation_RandomSphere ? static_cast<const Simulation::RandomSphere *>(location()) : nullptr;
  }
  const Simulation::Vec3Range *linear_velocity() const {
    return GetStruct<const Simulation::Vec3Range *>(VT_LINEAR_VELOCITY);
  }
  const Simulation::Vec3Range *angular_velocity() const {
    return GetStruct<const Simulation::Vec3Range *>(VT_ANGULAR_VELOCITY);
  }
  const ::flatbuffers::String *material() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL);
  }
  Simulation::SpawnerOwnerType owner() const {
    return static_cast<Simulation::SpawnerOwnerType>(GetField<int8_t>(VT_OWNER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_START_TIME, 4) &&
           VerifyField<uint8_t>(verifier, VT_SPAWN_TYPE_TYPE, 1) &&
           VerifyOffset(verifier, VT_SPAWN_TYPE) &&
           VerifySpawnType(verifier, spawn_type(), spawn_type_type()) &&
           VerifyField<uint8_t>(verifier, VT_LOCATION_TYPE, 1) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           VerifySpawnLocation(verifier, location(), location_type()) &&
           VerifyField<Simulation::Vec3Range>(verifier, VT_LINEAR_VELOCITY, 4) &&
           VerifyField<Simulation::Vec3Range>(verifier, VT_ANGULAR_VELOCITY, 4) &&
           VerifyOffset(verifier, VT_MATERIAL) &&
           verifier.VerifyString(material()) &&
           VerifyField<int8_t>(verifier, VT_OWNER, 1) &&
           verifier.EndTable();
  }
};

template<> inline const Simulation::SingleBurstSpawn *BaseSpawner::spawn_type_as<Simulation::SingleBurstSpawn>() const {
  return spawn_type_as_SingleBurstSpawn();
}

template<> inline const Simulation::RepeatingSpawn *BaseSpawner::spawn_type_as<Simulation::RepeatingSpawn>() const {
  return spawn_type_as_RepeatingSpawn();
}

template<> inline const Simulation::FixedLocation *BaseSpawner::location_as<Simulation::FixedLocation>() const {
  return location_as_FixedLocation();
}

template<> inline const Simulation::RandomBox *BaseSpawner::location_as<Simulation::RandomBox>() const {
  return location_as_RandomBox();
}

template<> inline const Simulation::RandomSphere *BaseSpawner::location_as<Simulation::RandomSphere>() const {
  return location_as_RandomSphere();
}

struct BaseSpawnerBuilder {
  typedef BaseSpawner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(BaseSpawner::VT_NAME, name);
  }
  void add_start_time(float start_time) {
    fbb_.AddElement<float>(BaseSpawner::VT_START_TIME, start_time, 0.0f);
  }
  void add_spawn_type_type(Simulation::SpawnType spawn_type_type) {
    fbb_.AddElement<uint8_t>(BaseSpawner::VT_SPAWN_TYPE_TYPE, static_cast<uint8_t>(spawn_type_type), 0);
  }
  void add_spawn_type(::flatbuffers::Offset<void> spawn_type) {
    fbb_.AddOffset(BaseSpawner::VT_SPAWN_TYPE, spawn_type);
  }
  void add_location_type(Simulation::SpawnLocation location_type) {
    fbb_.AddElement<uint8_t>(BaseSpawner::VT_LOCATION_TYPE, static_cast<uint8_t>(location_type), 0);
  }
  void add_location(::flatbuffers::Offset<void> location) {
    fbb_.AddOffset(BaseSpawner::VT_LOCATION, location);
  }
  void add_linear_velocity(const Simulation::Vec3Range *linear_velocity) {
    fbb_.AddStruct(BaseSpawner::VT_LINEAR_VELOCITY, linear_velocity);
  }
  void add_angular_velocity(const Simulation::Vec3Range *angular_velocity) {
    fbb_.AddStruct(BaseSpawner::VT_ANGULAR_VELOCITY, angular_velocity);
  }
  void add_material(::flatbuffers::Offset<::flatbuffers::String> material) {
    fbb_.AddOffset(BaseSpawner::VT_MATERIAL, material);
  }
  void add_owner(Simulation::SpawnerOwnerType owner) {
    fbb_.AddElement<int8_t>(BaseSpawner::VT_OWNER, static_cast<int8_t>(owner), 0);
  }
  explicit BaseSpawnerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BaseSpawner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BaseSpawner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BaseSpawner> CreateBaseSpawner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float start_time = 0.0f,
    Simulation::SpawnType spawn_type_type = Simulation::SpawnType_NONE,
    ::flatbuffers::Offset<void> spawn_type = 0,
    Simulation::SpawnLocation location_type = Simulation::SpawnLocation_NONE,
    ::flatbuffers::Offset<void> location = 0,
    const Simulation::Vec3Range *linear_velocity = nullptr,
    const Simulation::Vec3Range *angular_velocity = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> material = 0,
    Simulation::SpawnerOwnerType owner = Simulation::SpawnerOwnerType_ONE) {
  BaseSpawnerBuilder builder_(_fbb);
  builder_.add_material(material);
  builder_.add_angular_velocity(angular_velocity);
  builder_.add_linear_velocity(linear_velocity);
  builder_.add_location(location);
  builder_.add_spawn_type(spawn_type);
  builder_.add_start_time(start_time);
  builder_.add_name(name);
  builder_.add_owner(owner);
  builder_.add_location_type(location_type);
  builder_.add_spawn_type_type(spawn_type_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BaseSpawner> CreateBaseSpawnerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float start_time = 0.0f,
    Simulation::SpawnType spawn_type_type = Simulation::SpawnType_NONE,
    ::flatbuffers::Offset<void> spawn_type = 0,
    Simulation::SpawnLocation location_type = Simulation::SpawnLocation_NONE,
    ::flatbuffers::Offset<void> location = 0,
    const Simulation::Vec3Range *linear_velocity = nullptr,
    const Simulation::Vec3Range *angular_velocity = nullptr,
    const char *material = nullptr,
    Simulation::SpawnerOwnerType owner = Simulation::SpawnerOwnerType_ONE) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto material__ = material ? _fbb.CreateString(material) : 0;
  return Simulation::CreateBaseSpawner(
      _fbb,
      name__,
      start_time,
      spawn_type_type,
      spawn_type,
      location_type,
      location,
      linear_velocity,
      angular_velocity,
      material__,
      owner);
}

struct SphereSpawner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SphereSpawnerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_RADIUS_RANGE = 6
  };
  const Simulation::BaseSpawner *base() const {
    return GetPointer<const Simulation::BaseSpawner *>(VT_BASE);
  }
  const Simulation::FloatRange *radius_range() const {
    return GetStruct<const Simulation::FloatRange *>(VT_RADIUS_RANGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<Simulation::FloatRange>(verifier, VT_RADIUS_RANGE, 4) &&
           verifier.EndTable();
  }
};

struct SphereSpawnerBuilder {
  typedef SphereSpawner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<Simulation::BaseSpawner> base) {
    fbb_.AddOffset(SphereSpawner::VT_BASE, base);
  }
  void add_radius_range(const Simulation::FloatRange *radius_range) {
    fbb_.AddStruct(SphereSpawner::VT_RADIUS_RANGE, radius_range);
  }
  explicit SphereSpawnerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SphereSpawner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SphereSpawner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SphereSpawner> CreateSphereSpawner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Simulation::BaseSpawner> base = 0,
    const Simulation::FloatRange *radius_range = nullptr) {
  SphereSpawnerBuilder builder_(_fbb);
  builder_.add_radius_range(radius_range);
  builder_.add_base(base);
  return builder_.Finish();
}

struct CylinderSpawner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CylinderSpawnerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_RADIUS_RANGE = 6,
    VT_HEIGHT_RANGE = 8
  };
  const Simulation::BaseSpawner *base() const {
    return GetPointer<const Simulation::BaseSpawner *>(VT_BASE);
  }
  const Simulation::FloatRange *radius_range() const {
    return GetStruct<const Simulation::FloatRange *>(VT_RADIUS_RANGE);
  }
  const Simulation::FloatRange *height_range() const {
    return GetStruct<const Simulation::FloatRange *>(VT_HEIGHT_RANGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<Simulation::FloatRange>(verifier, VT_RADIUS_RANGE, 4) &&
           VerifyField<Simulation::FloatRange>(verifier, VT_HEIGHT_RANGE, 4) &&
           verifier.EndTable();
  }
};

struct CylinderSpawnerBuilder {
  typedef CylinderSpawner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<Simulation::BaseSpawner> base) {
    fbb_.AddOffset(CylinderSpawner::VT_BASE, base);
  }
  void add_radius_range(const Simulation::FloatRange *radius_range) {
    fbb_.AddStruct(CylinderSpawner::VT_RADIUS_RANGE, radius_range);
  }
  void add_height_range(const Simulation::FloatRange *height_range) {
    fbb_.AddStruct(CylinderSpawner::VT_HEIGHT_RANGE, height_range);
  }
  explicit CylinderSpawnerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CylinderSpawner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CylinderSpawner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CylinderSpawner> CreateCylinderSpawner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Simulation::BaseSpawner> base = 0,
    const Simulation::FloatRange *radius_range = nullptr,
    const Simulation::FloatRange *height_range = nullptr) {
  CylinderSpawnerBuilder builder_(_fbb);
  builder_.add_height_range(height_range);
  builder_.add_radius_range(radius_range);
  builder_.add_base(base);
  return builder_.Finish();
}

struct CapsuleSpawner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CapsuleSpawnerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_RADIUS_RANGE = 6,
    VT_HEIGHT_RANGE = 8
  };
  const Simulation::BaseSpawner *base() const {
    return GetPointer<const Simulation::BaseSpawner *>(VT_BASE);
  }
  const Simulation::FloatRange *radius_range() const {
    return GetStruct<const Simulation::FloatRange *>(VT_RADIUS_RANGE);
  }
  const Simulation::FloatRange *height_range() const {
    return GetStruct<const Simulation::FloatRange *>(VT_HEIGHT_RANGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<Simulation::FloatRange>(verifier, VT_RADIUS_RANGE, 4) &&
           VerifyField<Simulation::FloatRange>(verifier, VT_HEIGHT_RANGE, 4) &&
           verifier.EndTable();
  }
};

struct CapsuleSpawnerBuilder {
  typedef CapsuleSpawner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<Simulation::BaseSpawner> base) {
    fbb_.AddOffset(CapsuleSpawner::VT_BASE, base);
  }
  void add_radius_range(const Simulation::FloatRange *radius_range) {
    fbb_.AddStruct(CapsuleSpawner::VT_RADIUS_RANGE, radius_range);
  }
  void add_height_range(const Simulation::FloatRange *height_range) {
    fbb_.AddStruct(CapsuleSpawner::VT_HEIGHT_RANGE, height_range);
  }
  explicit CapsuleSpawnerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CapsuleSpawner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CapsuleSpawner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CapsuleSpawner> CreateCapsuleSpawner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Simulation::BaseSpawner> base = 0,
    const Simulation::FloatRange *radius_range = nullptr,
    const Simulation::FloatRange *height_range = nullptr) {
  CapsuleSpawnerBuilder builder_(_fbb);
  builder_.add_height_range(height_range);
  builder_.add_radius_range(radius_range);
  builder_.add_base(base);
  return builder_.Finish();
}

struct CuboidSpawner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CuboidSpawnerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_SIZE_RANGE = 6
  };
  const Simulation::BaseSpawner *base() const {
    return GetPointer<const Simulation::BaseSpawner *>(VT_BASE);
  }
  const Simulation::Vec3Range *size_range() const {
    return GetStruct<const Simulation::Vec3Range *>(VT_SIZE_RANGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<Simulation::Vec3Range>(verifier, VT_SIZE_RANGE, 4) &&
           verifier.EndTable();
  }
};

struct CuboidSpawnerBuilder {
  typedef CuboidSpawner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<Simulation::BaseSpawner> base) {
    fbb_.AddOffset(CuboidSpawner::VT_BASE, base);
  }
  void add_size_range(const Simulation::Vec3Range *size_range) {
    fbb_.AddStruct(CuboidSpawner::VT_SIZE_RANGE, size_range);
  }
  explicit CuboidSpawnerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CuboidSpawner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CuboidSpawner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CuboidSpawner> CreateCuboidSpawner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Simulation::BaseSpawner> base = 0,
    const Simulation::Vec3Range *size_range = nullptr) {
  CuboidSpawnerBuilder builder_(_fbb);
  builder_.add_size_range(size_range);
  builder_.add_base(base);
  return builder_.Finish();
}

struct Scene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_GRAVITY_ON = 8,
    VT_CAMERAS = 10,
    VT_OBJECTS = 12,
    VT_SPAWNERS_TYPE = 14,
    VT_SPAWNERS = 16,
    VT_MATERIALS = 18,
    VT_INTERACTIONS = 20
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  bool gravity_on() const {
    return GetField<uint8_t>(VT_GRAVITY_ON, 1) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Camera>> *cameras() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Camera>> *>(VT_CAMERAS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Object>> *objects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Object>> *>(VT_OBJECTS);
  }
  const ::flatbuffers::Vector<uint8_t> *spawners_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SPAWNERS_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *spawners() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_SPAWNERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Material>> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Material>> *>(VT_MATERIALS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::MaterialInteraction>> *interactions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Simulation::MaterialInteraction>> *>(VT_INTERACTIONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint8_t>(verifier, VT_GRAVITY_ON, 1) &&
           VerifyOffset(verifier, VT_CAMERAS) &&
           verifier.VerifyVector(cameras()) &&
           verifier.VerifyVectorOfTables(cameras()) &&
           VerifyOffset(verifier, VT_OBJECTS) &&
           verifier.VerifyVector(objects()) &&
           verifier.VerifyVectorOfTables(objects()) &&
           VerifyOffset(verifier, VT_SPAWNERS_TYPE) &&
           verifier.VerifyVector(spawners_type()) &&
           VerifyOffset(verifier, VT_SPAWNERS) &&
           verifier.VerifyVector(spawners()) &&
           VerifySpawnerTypeVector(verifier, spawners(), spawners_type()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           verifier.VerifyVectorOfTables(materials()) &&
           VerifyOffset(verifier, VT_INTERACTIONS) &&
           verifier.VerifyVector(interactions()) &&
           verifier.VerifyVectorOfTables(interactions()) &&
           verifier.EndTable();
  }
};

struct SceneBuilder {
  typedef Scene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Scene::VT_NAME, name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(Scene::VT_DESCRIPTION, description);
  }
  void add_gravity_on(bool gravity_on) {
    fbb_.AddElement<uint8_t>(Scene::VT_GRAVITY_ON, static_cast<uint8_t>(gravity_on), 1);
  }
  void add_cameras(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Camera>>> cameras) {
    fbb_.AddOffset(Scene::VT_CAMERAS, cameras);
  }
  void add_objects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Object>>> objects) {
    fbb_.AddOffset(Scene::VT_OBJECTS, objects);
  }
  void add_spawners_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> spawners_type) {
    fbb_.AddOffset(Scene::VT_SPAWNERS_TYPE, spawners_type);
  }
  void add_spawners(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> spawners) {
    fbb_.AddOffset(Scene::VT_SPAWNERS, spawners);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Material>>> materials) {
    fbb_.AddOffset(Scene::VT_MATERIALS, materials);
  }
  void add_interactions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::MaterialInteraction>>> interactions) {
    fbb_.AddOffset(Scene::VT_INTERACTIONS, interactions);
  }
  explicit SceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Scene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Scene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Scene> CreateScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    bool gravity_on = true,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Camera>>> cameras = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Object>>> objects = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> spawners_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> spawners = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::Material>>> materials = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Simulation::MaterialInteraction>>> interactions = 0) {
  SceneBuilder builder_(_fbb);
  builder_.add_interactions(interactions);
  builder_.add_materials(materials);
  builder_.add_spawners(spawners);
  builder_.add_spawners_type(spawners_type);
  builder_.add_objects(objects);
  builder_.add_cameras(cameras);
  builder_.add_description(description);
  builder_.add_name(name);
  builder_.add_gravity_on(gravity_on);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Scene> CreateSceneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *description = nullptr,
    bool gravity_on = true,
    const std::vector<::flatbuffers::Offset<Simulation::Camera>> *cameras = nullptr,
    const std::vector<::flatbuffers::Offset<Simulation::Object>> *objects = nullptr,
    const std::vector<uint8_t> *spawners_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *spawners = nullptr,
    const std::vector<::flatbuffers::Offset<Simulation::Material>> *materials = nullptr,
    const std::vector<::flatbuffers::Offset<Simulation::MaterialInteraction>> *interactions = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto cameras__ = cameras ? _fbb.CreateVector<::flatbuffers::Offset<Simulation::Camera>>(*cameras) : 0;
  auto objects__ = objects ? _fbb.CreateVector<::flatbuffers::Offset<Simulation::Object>>(*objects) : 0;
  auto spawners_type__ = spawners_type ? _fbb.CreateVector<uint8_t>(*spawners_type) : 0;
  auto spawners__ = spawners ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*spawners) : 0;
  auto materials__ = materials ? _fbb.CreateVector<::flatbuffers::Offset<Simulation::Material>>(*materials) : 0;
  auto interactions__ = interactions ? _fbb.CreateVector<::flatbuffers::Offset<Simulation::MaterialInteraction>>(*interactions) : 0;
  return Simulation::CreateScene(
      _fbb,
      name__,
      description__,
      gravity_on,
      cameras__,
      objects__,
      spawners_type__,
      spawners__,
      materials__,
      interactions__);
}

template <bool B>
inline bool VerifyCameraType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, CameraType type) {
  switch (type) {
    case CameraType_NONE: {
      return true;
    }
    case CameraType_PerspectiveCamera: {
      auto ptr = reinterpret_cast<const Simulation::PerspectiveCamera *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CameraType_OrthographicCamera: {
      auto ptr = reinterpret_cast<const Simulation::OrthographicCamera *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCameraTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCameraType(
        verifier,  values->Get(i), types->GetEnum<CameraType>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifyShape(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Shape type) {
  switch (type) {
    case Shape_NONE: {
      return true;
    }
    case Shape_Sphere: {
      auto ptr = reinterpret_cast<const Simulation::Sphere *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Shape_Plane: {
      auto ptr = reinterpret_cast<const Simulation::Plane *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Shape_Capsule: {
      auto ptr = reinterpret_cast<const Simulation::Capsule *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Shape_Cylinder: {
      auto ptr = reinterpret_cast<const Simulation::Cylinder *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Shape_Cuboid: {
      auto ptr = reinterpret_cast<const Simulation::Cuboid *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyShapeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyShape(
        verifier,  values->Get(i), types->GetEnum<Shape>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifyBehaviour(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Behaviour type) {
  switch (type) {
    case Behaviour_NONE: {
      return true;
    }
    case Behaviour_StaticObject: {
      auto ptr = reinterpret_cast<const Simulation::StaticObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Behaviour_SimulatedObject: {
      auto ptr = reinterpret_cast<const Simulation::SimulatedObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Behaviour_AnimatedObject: {
      auto ptr = reinterpret_cast<const Simulation::AnimatedObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyBehaviourVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyBehaviour(
        verifier,  values->Get(i), types->GetEnum<Behaviour>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifySpawnType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnType type) {
  switch (type) {
    case SpawnType_NONE: {
      return true;
    }
    case SpawnType_SingleBurstSpawn: {
      auto ptr = reinterpret_cast<const Simulation::SingleBurstSpawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnType_RepeatingSpawn: {
      auto ptr = reinterpret_cast<const Simulation::RepeatingSpawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySpawnTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySpawnType(
        verifier,  values->Get(i), types->GetEnum<SpawnType>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifySpawnLocation(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnLocation type) {
  switch (type) {
    case SpawnLocation_NONE: {
      return true;
    }
    case SpawnLocation_FixedLocation: {
      auto ptr = reinterpret_cast<const Simulation::FixedLocation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnLocation_RandomBox: {
      auto ptr = reinterpret_cast<const Simulation::RandomBox *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnLocation_RandomSphere: {
      auto ptr = reinterpret_cast<const Simulation::RandomSphere *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySpawnLocationVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySpawnLocation(
        verifier,  values->Get(i), types->GetEnum<SpawnLocation>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifySpawnerType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SpawnerType type) {
  switch (type) {
    case SpawnerType_NONE: {
      return true;
    }
    case SpawnerType_SphereSpawner: {
      auto ptr = reinterpret_cast<const Simulation::SphereSpawner *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnerType_CylinderSpawner: {
      auto ptr = reinterpret_cast<const Simulation::CylinderSpawner *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnerType_CapsuleSpawner: {
      auto ptr = reinterpret_cast<const Simulation::CapsuleSpawner *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SpawnerType_CuboidSpawner: {
      auto ptr = reinterpret_cast<const Simulation::CuboidSpawner *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySpawnerTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySpawnerType(
        verifier,  values->Get(i), types->GetEnum<SpawnerType>(i))) {
      return false;
    }
  }
  return true;
}

inline const Simulation::Scene *GetScene(const void *buf) {
  return ::flatbuffers::GetRoot<Simulation::Scene>(buf);
}

inline const Simulation::Scene *GetSizePrefixedScene(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Simulation::Scene>(buf);
}

template <bool B = false>
inline bool VerifySceneBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Simulation::Scene>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSceneBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Simulation::Scene>(nullptr);
}

inline void FinishSceneBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Simulation::Scene> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Simulation::Scene> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Simulation

#endif  // FLATBUFFERS_GENERATED_SCENE_SIMULATION_H_
