namespace SimulationNetwork;

table Vec3 {
  x:float;
  y:float;
  z:float;
}

table RotationEuler {
  yaw:float;
  pitch:float;
  roll:float;
}

table Transform {
  position:Vec3;
  orientation:RotationEuler;
  scale:Vec3;
}

table PhysicsState {
  linear_velocity:Vec3;
  angular_velocity:Vec3;
}

table EntityState {
  id:uint32;
  transform:Transform;
  physics:PhysicsState;
  owner:uint8;
  timestamp:double; // seconds
}

table StateBatch {
  states:[EntityState];
}

table SpawnRPC {
  template_name:string;
  owner:uint8;
  transform:Transform;
  initial_state:PhysicsState;
}

table SceneRPC { name:string; }

root_type StateBatch;
