// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NET_SIMULATIONNETWORK_H_
#define FLATBUFFERS_GENERATED_NET_SIMULATIONNETWORK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace SimulationNetwork {

struct Vec3;
struct Vec3Builder;

struct RotationEuler;
struct RotationEulerBuilder;

struct Transform;
struct TransformBuilder;

struct PhysicsState;
struct PhysicsStateBuilder;

struct EntityState;
struct EntityStateBuilder;

struct StateBatch;
struct StateBatchBuilder;

struct SpawnRPC;
struct SpawnRPCBuilder;

struct SceneRPC;
struct SceneRPCBuilder;

struct Vec3 FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3Builder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct Vec3Builder {
  typedef Vec3 Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3::VT_Z, z, 0.0f);
  }
  explicit Vec3Builder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3> CreateVec3(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3Builder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct RotationEuler FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RotationEulerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_YAW = 4,
    VT_PITCH = 6,
    VT_ROLL = 8
  };
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  float roll() const {
    return GetField<float>(VT_ROLL, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyField<float>(verifier, VT_PITCH, 4) &&
           VerifyField<float>(verifier, VT_ROLL, 4) &&
           verifier.EndTable();
  }
};

struct RotationEulerBuilder {
  typedef RotationEuler Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(RotationEuler::VT_YAW, yaw, 0.0f);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(RotationEuler::VT_PITCH, pitch, 0.0f);
  }
  void add_roll(float roll) {
    fbb_.AddElement<float>(RotationEuler::VT_ROLL, roll, 0.0f);
  }
  explicit RotationEulerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RotationEuler> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RotationEuler>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RotationEuler> CreateRotationEuler(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float yaw = 0.0f,
    float pitch = 0.0f,
    float roll = 0.0f) {
  RotationEulerBuilder builder_(_fbb);
  builder_.add_roll(roll);
  builder_.add_pitch(pitch);
  builder_.add_yaw(yaw);
  return builder_.Finish();
}

struct Transform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ORIENTATION = 6,
    VT_SCALE = 8
  };
  const SimulationNetwork::Vec3 *position() const {
    return GetPointer<const SimulationNetwork::Vec3 *>(VT_POSITION);
  }
  const SimulationNetwork::RotationEuler *orientation() const {
    return GetPointer<const SimulationNetwork::RotationEuler *>(VT_ORIENTATION);
  }
  const SimulationNetwork::Vec3 *scale() const {
    return GetPointer<const SimulationNetwork::Vec3 *>(VT_SCALE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyOffset(verifier, VT_SCALE) &&
           verifier.VerifyTable(scale()) &&
           verifier.EndTable();
  }
};

struct TransformBuilder {
  typedef Transform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<SimulationNetwork::Vec3> position) {
    fbb_.AddOffset(Transform::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<SimulationNetwork::RotationEuler> orientation) {
    fbb_.AddOffset(Transform::VT_ORIENTATION, orientation);
  }
  void add_scale(::flatbuffers::Offset<SimulationNetwork::Vec3> scale) {
    fbb_.AddOffset(Transform::VT_SCALE, scale);
  }
  explicit TransformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Transform> CreateTransform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<SimulationNetwork::Vec3> position = 0,
    ::flatbuffers::Offset<SimulationNetwork::RotationEuler> orientation = 0,
    ::flatbuffers::Offset<SimulationNetwork::Vec3> scale = 0) {
  TransformBuilder builder_(_fbb);
  builder_.add_scale(scale);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  return builder_.Finish();
}

struct PhysicsState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LINEAR_VELOCITY = 4,
    VT_ANGULAR_VELOCITY = 6
  };
  const SimulationNetwork::Vec3 *linear_velocity() const {
    return GetPointer<const SimulationNetwork::Vec3 *>(VT_LINEAR_VELOCITY);
  }
  const SimulationNetwork::Vec3 *angular_velocity() const {
    return GetPointer<const SimulationNetwork::Vec3 *>(VT_ANGULAR_VELOCITY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LINEAR_VELOCITY) &&
           verifier.VerifyTable(linear_velocity()) &&
           VerifyOffset(verifier, VT_ANGULAR_VELOCITY) &&
           verifier.VerifyTable(angular_velocity()) &&
           verifier.EndTable();
  }
};

struct PhysicsStateBuilder {
  typedef PhysicsState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_linear_velocity(::flatbuffers::Offset<SimulationNetwork::Vec3> linear_velocity) {
    fbb_.AddOffset(PhysicsState::VT_LINEAR_VELOCITY, linear_velocity);
  }
  void add_angular_velocity(::flatbuffers::Offset<SimulationNetwork::Vec3> angular_velocity) {
    fbb_.AddOffset(PhysicsState::VT_ANGULAR_VELOCITY, angular_velocity);
  }
  explicit PhysicsStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsState> CreatePhysicsState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<SimulationNetwork::Vec3> linear_velocity = 0,
    ::flatbuffers::Offset<SimulationNetwork::Vec3> angular_velocity = 0) {
  PhysicsStateBuilder builder_(_fbb);
  builder_.add_angular_velocity(angular_velocity);
  builder_.add_linear_velocity(linear_velocity);
  return builder_.Finish();
}

struct EntityState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TRANSFORM = 6,
    VT_PHYSICS = 8,
    VT_OWNER = 10,
    VT_TIMESTAMP = 12
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const SimulationNetwork::Transform *transform() const {
    return GetPointer<const SimulationNetwork::Transform *>(VT_TRANSFORM);
  }
  const SimulationNetwork::PhysicsState *physics() const {
    return GetPointer<const SimulationNetwork::PhysicsState *>(VT_PHYSICS);
  }
  uint8_t owner() const {
    return GetField<uint8_t>(VT_OWNER, 0);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyTable(transform()) &&
           VerifyOffset(verifier, VT_PHYSICS) &&
           verifier.VerifyTable(physics()) &&
           VerifyField<uint8_t>(verifier, VT_OWNER, 1) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct EntityStateBuilder {
  typedef EntityState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(EntityState::VT_ID, id, 0);
  }
  void add_transform(::flatbuffers::Offset<SimulationNetwork::Transform> transform) {
    fbb_.AddOffset(EntityState::VT_TRANSFORM, transform);
  }
  void add_physics(::flatbuffers::Offset<SimulationNetwork::PhysicsState> physics) {
    fbb_.AddOffset(EntityState::VT_PHYSICS, physics);
  }
  void add_owner(uint8_t owner) {
    fbb_.AddElement<uint8_t>(EntityState::VT_OWNER, owner, 0);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(EntityState::VT_TIMESTAMP, timestamp, 0.0);
  }
  explicit EntityStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityState> CreateEntityState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<SimulationNetwork::Transform> transform = 0,
    ::flatbuffers::Offset<SimulationNetwork::PhysicsState> physics = 0,
    uint8_t owner = 0,
    double timestamp = 0.0) {
  EntityStateBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_physics(physics);
  builder_.add_transform(transform);
  builder_.add_id(id);
  builder_.add_owner(owner);
  return builder_.Finish();
}

struct StateBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<SimulationNetwork::EntityState>> *states() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SimulationNetwork::EntityState>> *>(VT_STATES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STATES) &&
           verifier.VerifyVector(states()) &&
           verifier.VerifyVectorOfTables(states()) &&
           verifier.EndTable();
  }
};

struct StateBatchBuilder {
  typedef StateBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_states(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SimulationNetwork::EntityState>>> states) {
    fbb_.AddOffset(StateBatch::VT_STATES, states);
  }
  explicit StateBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateBatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateBatch> CreateStateBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SimulationNetwork::EntityState>>> states = 0) {
  StateBatchBuilder builder_(_fbb);
  builder_.add_states(states);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StateBatch> CreateStateBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<SimulationNetwork::EntityState>> *states = nullptr) {
  auto states__ = states ? _fbb.CreateVector<::flatbuffers::Offset<SimulationNetwork::EntityState>>(*states) : 0;
  return SimulationNetwork::CreateStateBatch(
      _fbb,
      states__);
}

struct SpawnRPC FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpawnRPCBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEMPLATE_NAME = 4,
    VT_OWNER = 6,
    VT_TRANSFORM = 8,
    VT_INITIAL_STATE = 10
  };
  const ::flatbuffers::String *template_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEMPLATE_NAME);
  }
  uint8_t owner() const {
    return GetField<uint8_t>(VT_OWNER, 0);
  }
  const SimulationNetwork::Transform *transform() const {
    return GetPointer<const SimulationNetwork::Transform *>(VT_TRANSFORM);
  }
  const SimulationNetwork::PhysicsState *initial_state() const {
    return GetPointer<const SimulationNetwork::PhysicsState *>(VT_INITIAL_STATE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEMPLATE_NAME) &&
           verifier.VerifyString(template_name()) &&
           VerifyField<uint8_t>(verifier, VT_OWNER, 1) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyTable(transform()) &&
           VerifyOffset(verifier, VT_INITIAL_STATE) &&
           verifier.VerifyTable(initial_state()) &&
           verifier.EndTable();
  }
};

struct SpawnRPCBuilder {
  typedef SpawnRPC Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_template_name(::flatbuffers::Offset<::flatbuffers::String> template_name) {
    fbb_.AddOffset(SpawnRPC::VT_TEMPLATE_NAME, template_name);
  }
  void add_owner(uint8_t owner) {
    fbb_.AddElement<uint8_t>(SpawnRPC::VT_OWNER, owner, 0);
  }
  void add_transform(::flatbuffers::Offset<SimulationNetwork::Transform> transform) {
    fbb_.AddOffset(SpawnRPC::VT_TRANSFORM, transform);
  }
  void add_initial_state(::flatbuffers::Offset<SimulationNetwork::PhysicsState> initial_state) {
    fbb_.AddOffset(SpawnRPC::VT_INITIAL_STATE, initial_state);
  }
  explicit SpawnRPCBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpawnRPC> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpawnRPC>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpawnRPC> CreateSpawnRPC(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> template_name = 0,
    uint8_t owner = 0,
    ::flatbuffers::Offset<SimulationNetwork::Transform> transform = 0,
    ::flatbuffers::Offset<SimulationNetwork::PhysicsState> initial_state = 0) {
  SpawnRPCBuilder builder_(_fbb);
  builder_.add_initial_state(initial_state);
  builder_.add_transform(transform);
  builder_.add_template_name(template_name);
  builder_.add_owner(owner);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SpawnRPC> CreateSpawnRPCDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *template_name = nullptr,
    uint8_t owner = 0,
    ::flatbuffers::Offset<SimulationNetwork::Transform> transform = 0,
    ::flatbuffers::Offset<SimulationNetwork::PhysicsState> initial_state = 0) {
  auto template_name__ = template_name ? _fbb.CreateString(template_name) : 0;
  return SimulationNetwork::CreateSpawnRPC(
      _fbb,
      template_name__,
      owner,
      transform,
      initial_state);
}

struct SceneRPC FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneRPCBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct SceneRPCBuilder {
  typedef SceneRPC Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SceneRPC::VT_NAME, name);
  }
  explicit SceneRPCBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneRPC> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneRPC>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneRPC> CreateSceneRPC(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  SceneRPCBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneRPC> CreateSceneRPCDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return SimulationNetwork::CreateSceneRPC(
      _fbb,
      name__);
}

inline const SimulationNetwork::StateBatch *GetStateBatch(const void *buf) {
  return ::flatbuffers::GetRoot<SimulationNetwork::StateBatch>(buf);
}

inline const SimulationNetwork::StateBatch *GetSizePrefixedStateBatch(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SimulationNetwork::StateBatch>(buf);
}

template <bool B = false>
inline bool VerifyStateBatchBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<SimulationNetwork::StateBatch>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedStateBatchBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<SimulationNetwork::StateBatch>(nullptr);
}

inline void FinishStateBatchBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SimulationNetwork::StateBatch> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStateBatchBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SimulationNetwork::StateBatch> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SimulationNetwork

#endif  // FLATBUFFERS_GENERATED_NET_SIMULATIONNETWORK_H_
