// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NETWORKSCHEMA_VULKANPHYSICS_NETWORK_H_
#define FLATBUFFERS_GENERATED_NETWORKSCHEMA_VULKANPHYSICS_NETWORK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace VulkanPhysics {
namespace Network {

struct Vec3;

struct EntityState;
struct EntityStateBuilder;

struct PhysicsSnapshot;
struct PhysicsSnapshotBuilder;

struct ReliableEvent;
struct ReliableEventBuilder;

struct NetworkMessage;
struct NetworkMessageBuilder;

enum EventType : int8_t {
  EventType_SceneLoad = 0,
  EventType_SpawnObject = 1,
  EventType_DespawnObject = 2,
  EventType_IdAssignment = 3,
  EventType_RuntimeControl = 4,
  EventType_MIN = EventType_SceneLoad,
  EventType_MAX = EventType_RuntimeControl
};

inline const EventType (&EnumValuesEventType())[5] {
  static const EventType values[] = {
    EventType_SceneLoad,
    EventType_SpawnObject,
    EventType_DespawnObject,
    EventType_IdAssignment,
    EventType_RuntimeControl
  };
  return values;
}

inline const char * const *EnumNamesEventType() {
  static const char * const names[6] = {
    "SceneLoad",
    "SpawnObject",
    "DespawnObject",
    "IdAssignment",
    "RuntimeControl",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventType(EventType e) {
  if (::flatbuffers::IsOutRange(e, EventType_SceneLoad, EventType_RuntimeControl)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventType()[index];
}

enum Payload : uint8_t {
  Payload_NONE = 0,
  Payload_PhysicsSnapshot = 1,
  Payload_ReliableEvent = 2,
  Payload_MIN = Payload_NONE,
  Payload_MAX = Payload_ReliableEvent
};

inline const Payload (&EnumValuesPayload())[3] {
  static const Payload values[] = {
    Payload_NONE,
    Payload_PhysicsSnapshot,
    Payload_ReliableEvent
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[4] = {
    "NONE",
    "PhysicsSnapshot",
    "ReliableEvent",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload_NONE, Payload_ReliableEvent)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template<typename T> struct PayloadTraits {
  static const Payload enum_value = Payload_NONE;
};

template<> struct PayloadTraits<VulkanPhysics::Network::PhysicsSnapshot> {
  static const Payload enum_value = Payload_PhysicsSnapshot;
};

template<> struct PayloadTraits<VulkanPhysics::Network::ReliableEvent> {
  static const Payload enum_value = Payload_ReliableEvent;
};

template <bool B = false>
bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type);
template <bool B = false>
bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct EntityState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_OWNER = 6,
    VT_POSITION = 8,
    VT_ROTATION = 10,
    VT_LINEAR_VELOCITY = 12,
    VT_ANGULAR_VELOCITY = 14
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  int8_t owner() const {
    return GetField<int8_t>(VT_OWNER, 0);
  }
  const VulkanPhysics::Network::Vec3 *position() const {
    return GetStruct<const VulkanPhysics::Network::Vec3 *>(VT_POSITION);
  }
  const VulkanPhysics::Network::Vec3 *rotation() const {
    return GetStruct<const VulkanPhysics::Network::Vec3 *>(VT_ROTATION);
  }
  const VulkanPhysics::Network::Vec3 *linear_velocity() const {
    return GetStruct<const VulkanPhysics::Network::Vec3 *>(VT_LINEAR_VELOCITY);
  }
  const VulkanPhysics::Network::Vec3 *angular_velocity() const {
    return GetStruct<const VulkanPhysics::Network::Vec3 *>(VT_ANGULAR_VELOCITY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_OWNER, 1) &&
           VerifyField<VulkanPhysics::Network::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<VulkanPhysics::Network::Vec3>(verifier, VT_ROTATION, 4) &&
           VerifyField<VulkanPhysics::Network::Vec3>(verifier, VT_LINEAR_VELOCITY, 4) &&
           VerifyField<VulkanPhysics::Network::Vec3>(verifier, VT_ANGULAR_VELOCITY, 4) &&
           verifier.EndTable();
  }
};

struct EntityStateBuilder {
  typedef EntityState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(EntityState::VT_ENTITY_ID, entity_id, 0);
  }
  void add_owner(int8_t owner) {
    fbb_.AddElement<int8_t>(EntityState::VT_OWNER, owner, 0);
  }
  void add_position(const VulkanPhysics::Network::Vec3 *position) {
    fbb_.AddStruct(EntityState::VT_POSITION, position);
  }
  void add_rotation(const VulkanPhysics::Network::Vec3 *rotation) {
    fbb_.AddStruct(EntityState::VT_ROTATION, rotation);
  }
  void add_linear_velocity(const VulkanPhysics::Network::Vec3 *linear_velocity) {
    fbb_.AddStruct(EntityState::VT_LINEAR_VELOCITY, linear_velocity);
  }
  void add_angular_velocity(const VulkanPhysics::Network::Vec3 *angular_velocity) {
    fbb_.AddStruct(EntityState::VT_ANGULAR_VELOCITY, angular_velocity);
  }
  explicit EntityStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityState> CreateEntityState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    int8_t owner = 0,
    const VulkanPhysics::Network::Vec3 *position = nullptr,
    const VulkanPhysics::Network::Vec3 *rotation = nullptr,
    const VulkanPhysics::Network::Vec3 *linear_velocity = nullptr,
    const VulkanPhysics::Network::Vec3 *angular_velocity = nullptr) {
  EntityStateBuilder builder_(_fbb);
  builder_.add_angular_velocity(angular_velocity);
  builder_.add_linear_velocity(linear_velocity);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  builder_.add_owner(owner);
  return builder_.Finish();
}

struct PhysicsSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicsSnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE_NUMBER = 4,
    VT_TICK_INDEX = 6,
    VT_STATES = 8
  };
  uint32_t sequence_number() const {
    return GetField<uint32_t>(VT_SEQUENCE_NUMBER, 0);
  }
  uint64_t tick_index() const {
    return GetField<uint64_t>(VT_TICK_INDEX, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>> *states() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>> *>(VT_STATES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE_NUMBER, 4) &&
           VerifyField<uint64_t>(verifier, VT_TICK_INDEX, 8) &&
           VerifyOffset(verifier, VT_STATES) &&
           verifier.VerifyVector(states()) &&
           verifier.VerifyVectorOfTables(states()) &&
           verifier.EndTable();
  }
};

struct PhysicsSnapshotBuilder {
  typedef PhysicsSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sequence_number(uint32_t sequence_number) {
    fbb_.AddElement<uint32_t>(PhysicsSnapshot::VT_SEQUENCE_NUMBER, sequence_number, 0);
  }
  void add_tick_index(uint64_t tick_index) {
    fbb_.AddElement<uint64_t>(PhysicsSnapshot::VT_TICK_INDEX, tick_index, 0);
  }
  void add_states(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>>> states) {
    fbb_.AddOffset(PhysicsSnapshot::VT_STATES, states);
  }
  explicit PhysicsSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicsSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicsSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicsSnapshot> CreatePhysicsSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sequence_number = 0,
    uint64_t tick_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>>> states = 0) {
  PhysicsSnapshotBuilder builder_(_fbb);
  builder_.add_tick_index(tick_index);
  builder_.add_states(states);
  builder_.add_sequence_number(sequence_number);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PhysicsSnapshot> CreatePhysicsSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sequence_number = 0,
    uint64_t tick_index = 0,
    const std::vector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>> *states = nullptr) {
  auto states__ = states ? _fbb.CreateVector<::flatbuffers::Offset<VulkanPhysics::Network::EntityState>>(*states) : 0;
  return VulkanPhysics::Network::CreatePhysicsSnapshot(
      _fbb,
      sequence_number,
      tick_index,
      states__);
}

struct ReliableEvent FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReliableEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_TYPE = 4,
    VT_STRING_PAYLOAD = 6,
    VT_TARGET_ENTITY_ID = 8
  };
  VulkanPhysics::Network::EventType event_type() const {
    return static_cast<VulkanPhysics::Network::EventType>(GetField<int8_t>(VT_EVENT_TYPE, 0));
  }
  const ::flatbuffers::String *string_payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STRING_PAYLOAD);
  }
  uint32_t target_entity_id() const {
    return GetField<uint32_t>(VT_TARGET_ENTITY_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_EVENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_STRING_PAYLOAD) &&
           verifier.VerifyString(string_payload()) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_ENTITY_ID, 4) &&
           verifier.EndTable();
  }
};

struct ReliableEventBuilder {
  typedef ReliableEvent Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_event_type(VulkanPhysics::Network::EventType event_type) {
    fbb_.AddElement<int8_t>(ReliableEvent::VT_EVENT_TYPE, static_cast<int8_t>(event_type), 0);
  }
  void add_string_payload(::flatbuffers::Offset<::flatbuffers::String> string_payload) {
    fbb_.AddOffset(ReliableEvent::VT_STRING_PAYLOAD, string_payload);
  }
  void add_target_entity_id(uint32_t target_entity_id) {
    fbb_.AddElement<uint32_t>(ReliableEvent::VT_TARGET_ENTITY_ID, target_entity_id, 0);
  }
  explicit ReliableEventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReliableEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReliableEvent>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReliableEvent> CreateReliableEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    VulkanPhysics::Network::EventType event_type = VulkanPhysics::Network::EventType_SceneLoad,
    ::flatbuffers::Offset<::flatbuffers::String> string_payload = 0,
    uint32_t target_entity_id = 0) {
  ReliableEventBuilder builder_(_fbb);
  builder_.add_target_entity_id(target_entity_id);
  builder_.add_string_payload(string_payload);
  builder_.add_event_type(event_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReliableEvent> CreateReliableEventDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    VulkanPhysics::Network::EventType event_type = VulkanPhysics::Network::EventType_SceneLoad,
    const char *string_payload = nullptr,
    uint32_t target_entity_id = 0) {
  auto string_payload__ = string_payload ? _fbb.CreateString(string_payload) : 0;
  return VulkanPhysics::Network::CreateReliableEvent(
      _fbb,
      event_type,
      string_payload__,
      target_entity_id);
}

struct NetworkMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetworkMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_PEER_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  int8_t sender_peer_id() const {
    return GetField<int8_t>(VT_SENDER_PEER_ID, 0);
  }
  VulkanPhysics::Network::Payload payload_type() const {
    return static_cast<VulkanPhysics::Network::Payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const VulkanPhysics::Network::PhysicsSnapshot *payload_as_PhysicsSnapshot() const {
    return payload_type() == VulkanPhysics::Network::Payload_PhysicsSnapshot ? static_cast<const VulkanPhysics::Network::PhysicsSnapshot *>(payload()) : nullptr;
  }
  const VulkanPhysics::Network::ReliableEvent *payload_as_ReliableEvent() const {
    return payload_type() == VulkanPhysics::Network::Payload_ReliableEvent ? static_cast<const VulkanPhysics::Network::ReliableEvent *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SENDER_PEER_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const VulkanPhysics::Network::PhysicsSnapshot *NetworkMessage::payload_as<VulkanPhysics::Network::PhysicsSnapshot>() const {
  return payload_as_PhysicsSnapshot();
}

template<> inline const VulkanPhysics::Network::ReliableEvent *NetworkMessage::payload_as<VulkanPhysics::Network::ReliableEvent>() const {
  return payload_as_ReliableEvent();
}

struct NetworkMessageBuilder {
  typedef NetworkMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_peer_id(int8_t sender_peer_id) {
    fbb_.AddElement<int8_t>(NetworkMessage::VT_SENDER_PEER_ID, sender_peer_id, 0);
  }
  void add_payload_type(VulkanPhysics::Network::Payload payload_type) {
    fbb_.AddElement<uint8_t>(NetworkMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(NetworkMessage::VT_PAYLOAD, payload);
  }
  explicit NetworkMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetworkMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetworkMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetworkMessage> CreateNetworkMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int8_t sender_peer_id = 0,
    VulkanPhysics::Network::Payload payload_type = VulkanPhysics::Network::Payload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  NetworkMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  builder_.add_sender_peer_id(sender_peer_id);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload_NONE: {
      return true;
    }
    case Payload_PhysicsSnapshot: {
      auto ptr = reinterpret_cast<const VulkanPhysics::Network::PhysicsSnapshot *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_ReliableEvent: {
      auto ptr = reinterpret_cast<const VulkanPhysics::Network::ReliableEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline const VulkanPhysics::Network::NetworkMessage *GetNetworkMessage(const void *buf) {
  return ::flatbuffers::GetRoot<VulkanPhysics::Network::NetworkMessage>(buf);
}

inline const VulkanPhysics::Network::NetworkMessage *GetSizePrefixedNetworkMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VulkanPhysics::Network::NetworkMessage>(buf);
}

template <bool B = false>
inline bool VerifyNetworkMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<VulkanPhysics::Network::NetworkMessage>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedNetworkMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<VulkanPhysics::Network::NetworkMessage>(nullptr);
}

inline void FinishNetworkMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VulkanPhysics::Network::NetworkMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNetworkMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VulkanPhysics::Network::NetworkMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Network
}  // namespace VulkanPhysics

#endif  // FLATBUFFERS_GENERATED_NETWORKSCHEMA_VULKANPHYSICS_NETWORK_H_
